### ISSUE TITLE
Permissions problem with bitvise ssh server

### ISSUE THREAD

**Issue by binaryplease** [libfuse/sshfs#1]
Hi,

I cant edit files mounted over ssh from a bitvise sever. I tried a lot of combinations of options (uid, giud, idmap, allow_other) and can't get it right.

- Read Access works
- Deleting Files works
- Creating files works
- Editing (in vim) gives an permission error upon save.

Is this a bug or config problem?

**Comment by Nikratio** [comment]
What specific operation is causing the error? For example, does the following work?
```
# python 
fh = open('mountpoint/test_file', 'rb+')
fh.write(b'bla')
fh.close()
^D
```

**Comment by binaryplease** [comment]
Nevermind, I found the problem. BItvise SSH server logs the users in using "Virtual Accounts" not the default windows accounts. That's why my user could write the files on the system itself but not through ssh.

**Comment by Lillecarl** [comment]
For anyone googling BitWise SSH problems and ending up here.
https://www.bitvise.com/getting-started-config-sftp-scp
When you set up BitWise Virtual Users it'll create a Windows user called BvSsh_VirtualUsers and use it as security context for writing files, which means you must grant write access for that user on the directories you you set as Root Directory.

-bvshell: Root path on the server doesn't exist. Please check SSH Server configuration.
^ SEO 2.0

**Comment by EpsilonCommunity** [comment]
How to allow Permissions for Ubuntu/Linux?
![image](https://user-images.githubusercontent.com/46479078/134777316-e7f9bb24-b386-4d80-9d7f-3a74fea8f55a.png)
