### ISSUE TITLE
configure not working

### ISSUE THREAD

**Issue by yarmenti** [libfuse/sshfs#10]
Hi,
I tried to configure sshfs after installing the prerequisites, but I couldn't succeed. It keeps saying me that glib2 dev is not installed... 

I'm on Ubuntu 15.10. Could you help me ? Thanks

**Comment by Nikratio** [comment]
Have you tried installing `libglib2.0-dev` or something like that? In any case, this doesn't seem to be a bug in sshfs.

**Comment by yarmenti** [comment]
Yes, this is what I did.
I installes first pkg manager using its own version of libs, then fuse (last release), afterwards I ran a 
`sudo apt-get install libglib2.0-dev`
and finally downloaded the last release version of sshfs, but couldn't make it.

I'll try to make a Dockerfile, with the command, seeing it it's still KO.

**Comment by yarmenti** [comment]
Well weird, it is OK with a Dockerfile I made.
I'll try to fix that on my VM.

Thanks,
