### ISSUE TITLE
sshfs edit hard link files problem

### ISSUE THREAD

**Issue by obarong** [libfuse/sshfs#107]
a.txt and b.txt are hard links on remote ubuntu server. I modified a.txt on sshfs, b.txt did not change.

sshfs version: 2.5-1ubuntu1
local system: Ubuntu 16.04 LTS
remote server system: Ubuntu 14.04.5 LTS

**Comment by Nikratio** [comment]
Thanks for taking the time to report this! I think this question is answered by the manpage:

```
CAVEATS / WORKAROUNDS
   Hardlinks
       If the SSH server supports the hardlinks extension,  SSHFS  will  allow
       you to create hardlinks. However, hardlinks will always appear as indi‐
       vidual files when seen through an SSHFS mount, i.e. they will appear to
       have different inodes and an st_nlink value of 1.

```
