### ISSUE TITLE
Enable noappledouble option by default

### ISSUE THREAD

**Issue by willmedtrainingsolutionscom** [libfuse/sshfs#108]
Use sshfs on a macOS client to connect to a Linux host. This results in `.DS_Store` files being littered on the host.

It appears Fuse has an option to disable this http://eddmann.com/posts/mounting-an-osx-ssh-volume-using-fuse-and-sshfs/

Can this be enabled by default by sshfs?

**Comment by Nikratio** [comment]
Technically this wouldn't be a problem. I'm not sure it's a good idea though, and I'm not a MacOS user. Doesn't this imply some sort of dataloss?

**Comment by fulldecent** [comment]
I'm not sure what is right to do here. But I'll say that Panic's new Transmit 5 does not leave Apple Double files on the server. Perhaps they can be trusted as a best practice.

**Comment by kalvdans** [comment]
I would prefer if sshfs doesn't filter certain filenames by default, I like that it is an option you need to enable.
