### ISSUE TITLE
Would it be possible to use cp --reflink if the remote filesystem supports reflinks?

### ISSUE THREAD

**Issue by etamponi** [libfuse/sshfs#113]
Hello,

I tried out sshfs because it is very easy to use, and fits perfectly my use case, except for one thing: the remote directory I am mounting is on a btrfs filesystem, which supports reflinks (copy on write). However, I cannot use `cp --reflink` from the sshfs-mounted directory. Would it be possible to add support for reflinks, if the underlying remote filesystem supports them?

I hope the question is clear!

I am also willing to provide help if needed :)

**Comment by Nikratio** [comment]
Thanks for the suggestion! That would be possible if the SFTP protocol supported a reflink operation. But as far as I know, it doesn't. If someone knows otherwise, please correct me.
