### ISSUE TITLE
May I ask how to get debug message in sshfs?

### ISSUE THREAD

**Issue by moonend** [libfuse/sshfs#115]
I want to block reading certain files which has specific extensions(etc: exe);

I tried to get debug msg to stdout/stderr, or file.
But I failed all the time. 

May I ask how to get debug message in sshfs?

**Comment by Nikratio** [comment]
$ ./sshfs --help | grep debug
    -d, --debug            print some debugging information (implies -f)

[0] nikratio@thinkpad:~/in-progress/sshfs/build
$ ./sshfs --version
SSHFS version 3.3.0
FUSE library version 3.2.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.2.0

If that's not giving you what you want, you'll have to give more details
about what's not working and what kind of debug messages you'd like to have.

But please use the mailing list for such questions, the bug tracker is intended for bugs :-)
