### ISSUE TITLE
ranlib crashes sshfs mount

### ISSUE THREAD

**Issue by g-raffy** [libfuse/sshfs#119]
It seems that ranlib does something to files that cause instabilities that could lead to an sshfs crash.

This bug was discovered on a debian 7 machine (sshfs 2.4-1, fuse 2.9.0-2+deb7u2), where the attached bash script (that's what I narrowed the problem down to) stops at random iteration with the following message :
...
test 31
/root/mnt/myshare_as_bobby/sshfs_ranlib_stresser_folder
bobby@my.server.com:/mnt/myshare on /root/mnt/myshare_as_bobby type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
test 32
/root/mnt/myshare_as_bobby/sshfs_ranlib_stresser_folder
bobby@my.server.com:/mnt/myshare on /root/mnt/myshare_as_bobby type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
test 33
ranlib: unable to rename './libwrappers.a'; reason: Software caused connection abort
ranlib failed

 at this point:
 1. the sshfs process has disappeared (even if the sshfs mount has been performed outside this script)
 2. the mount point is no longer usable (but can still be unmounted) :
     bobby@workstation# ls /root/mnt/myshare_as_bobby/sshfs_ranlib_stresser_folder
     ls: cannot access /root/mnt/myshare_as_bobby/sshfs_ranlib_stresser_folder: Transport endpoint is not connected

Maybe this bug has already been fixed as I never managed to make the script fail on a debian 9 machine (sshfs 2.8-1, fuse 2.9.7-1). However, as I couldn't find a bug report about this issue, I thought that you would be interested in this report.

Hope this helps

[sshfs_ranlib_stresser.bash.txt](https://github.com/libfuse/sshfs/files/1830112/sshfs_ranlib_stresser.bash.txt)

**Comment by g-raffy** [comment]
This bug was already submitted here but it's not clear whether it's been fixed or not :
https://bugs.launchpad.net/ubuntu/+source/sshfs-fuse/+bug/1063008

**Comment by Nikratio** [comment]
Thanks for the report! Could you please try to run sshfs in foreground under GDB so that we get a backtrace? `gdb sshfs -s -f <other options>` should do it.  Thanks!

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
