### ISSUE TITLE
Not specifying the mount location gives segmentation fault error instead of a more intelligible one

### ISSUE THREAD

**Issue by NightMachinary** [libfuse/sshfs#120]
Not specifying the mount location gives segmentation fault error instead of a more intelligible one.

**Comment by Nikratio** [comment]
Thanks for the report! Could you provide more details? I'm not sure how to reproduce the problem:

```
$ ./sshfs
missing host
see `./sshfs -h' for usage
$ ./sshfs foo
sshfs: bad mount point `foo': No such file or directory
$ ./sshfs --version
SSHFS version 3.3.1
FUSE library version 3.1.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.0

```

**Comment by NightMachinary** [comment]
I'm sorry, I had mistaken the repo: https://github.com/osxfuse/sshfs . Sorry! 👍🏻

**Comment by NightMachinary** [comment]
In fact I don't know which repo I am using :\ I installed sshfs via brew. How do I check? Looking at https://github.com/Homebrew/homebrew-core/blob/master/Formula/sshfs.rb suggests I actually have this installed.

**Comment by NightMachinary** [comment]
As for reproduction, run `sshfs 10.0.0.6:/Volumes/someName`.

**Comment by Nikratio** [comment]
Thanks for checking! Unfortunately I have no control over Brew, that's maintained by someone else entirely.
