### ISSUE TITLE
Unix domain socket forwarding

### ISSUE THREAD

**Issue by ageis** [libfuse/sshfs#125]
_(also posted to fuse-sshfs mailing list)_

## Feature request

I'd like to forward my gpg-agent socket (or any other Unix domain socket for that matter) using sshfs. I know how to do -o SSHOPT= on the command line, but how can I make it happen via `/etc/fstab`?

Let's assume this is what I have now:

```
sshfs#person@192.168.1.199:/home/person/.gnupg    /home/person/.gnupg    fuse.sshfs    defaults,user=person,x-systemd.automount,noauto,noatime,_netdev,cache=yes,IdentityFile=/home/person/.ssh/id_ed25519,StreamLocalBinUnlink=yes,ExitOnForwardFailure=yes,reconnect,uid=1001,gid=1001,idmap=user,allow_other,umask=002,LogLevel=VERBOSE,default_permissions,sync_readdir,dcache_timeout=300,kernel_cache,transform_symlinks,remember=300    0    0
```

In the first place, fuse doesn't recognize unknown option(s): `-o StreamLocalBinUnlink=yes,ExitOnForwardFailure=yes` which are OpenSSH client options...

Secondly, what else I'd like to add would look like this if run via ssh:

```
-R /home/person/.gnupg/S.gpg-agent:/home/person/.gnupg/gpg-agent.sock
```

(to make it simple let's assume the remote and host machine user accounts share a name+uid and I'm mounting a subfolder of their home directory or something, perhaps even `$GNUPGHOME` itself... The latter could be the equivalent of `$GPG_SOCK` in a shell, or a path from `gpg-agent --extra-socket`. So I'd be forwarding my local gpg-agent socket into the remote host whose directory I'm mounting via the fuse SSHFS driver, but the direction is unimportant since vice-versa would be cool too.

Would appreciate any help with attaining this configuration. For reference, the feature allowing one to do this landed in OpenSSH version 6.7 ([old site](http://25thandclement.com/~william/projects/streamlocal.html))

**Comment by ageis** [comment]
At a glance, it appears I might be able to use `ssh_command=ssh\040-vv`... Will edit this comment after I try that.

**Comment by Nikratio** [comment]
What exactly are you trying to do? SSHFS doesn't allow you to run commands on the server, so there is nothing that could take advantage of the forwarding.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please feel free to re-open this if you can provide the requested information!
