### ISSUE TITLE
sshfs always tries to connect when Nautilus is opened, even when delay_connect is set

### ISSUE THREAD

**Issue by jasonhansel** [libfuse/sshfs#126]
I'm currently trying to mount sshfs with delay_connect as follows:
```
 sshfs -f -d jason@server:/ ~/mnt_server -F ~/.ssh/config -o delay_connect
```
However, sshfs tries to connect *whenever* I open Nautilus, even if I don't actually open `~/mnt_server`. It appears that Nautilus's logic for detecting mounted devices accidentally triggers sshfs to initiate the connection. Using systemd to mask the gvfs units doesn't seem to help.

**Comment by Nikratio** [comment]
Thanks for the report! Unfortunately there is nothing SSHFS can do it - it can't tell what's a real request and what it should rather ignore. This would need to be addressed in Nautilus.
