### ISSUE TITLE
sshfs as upper fs using overlayroot

### ISSUE THREAD

**Issue by chrsch** [libfuse/sshfs#129]
Hi,

with sshfs 2.5 (shipped with Ubuntu 14.04) I used to mount overlayroot using a directory  mounted with sshfs as upper dir. Now with sshfs 3.3.2 (build from source on Ubuntu 16.04) this seems to be not possible any longer. Is this a known issue? Did sshfs drop something needed by overlayroot? Any thoughts?

Example
upper=/mnt/sshfs/some/path (sshfs fs)
lower=/usr/some/path (ext4 fs)
mount -t overlay -olowerdir=$lower upperdir=$upper,workdir=$upper/overlay_workdir/ overlay /var/overlayfs

This will result in error "overlayfs: filesystem on '/mnt/sshfs/some/path' not supported as upperdir"

**Comment by Nikratio** [comment]
Not sure what could cause this. Unfortunately the error message is not telling us anything useful either. Best way forward would be to debug on the overlayfs side and try to get more information about why the path isn't considered suitable..

Closing this bug for now, please do re-open if you find out more.
