### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by yarmenti** [libfuse/sshfs#13]
Hello,

I'd like to run a container which mount some folder by sshfs and share it via a volume.
I succeeded mounting the files in a directory inside the container (say /data/), but from my host, I can't see anything (running my docker container with -v /home/user/data:/data/).

Is it possible?

Thanks

**Comment by Nikratio** [comment]
This isn't a bug in sshfs, so please use the mailing list. As to your question: you may have to disable mount namespaces for the container, or try the `-o allow_other` option.

**Comment by yarmenti** [comment]
I don't see the mailing list here in Github; this is the reason I posted here.
Thanks, I'll try.

**Comment by Nikratio** [comment]
Use the fuse mailing list, your problem is not sshfs specific. Sorry, forgot to mention that.
