### ISSUE TITLE
can not mount any directory, mount: according to mtab, xxx is already mounted on yyy

### ISSUE THREAD

**Issue by sanyechong** [libfuse/sshfs#131]
In a ubuntu14.04 machine, I can not mount any directory using sshfs. When I try sshfs, I get:
> sshfs -o remount 10.8.24.3:/remote_data /remote_data/
mount: according to mtab, 10.8.24.3:/remote_data is already mounted on /remote_data

Then I change some args, the result is the same:
> sshfs aabb:sdf /remote_data/
mount: according to mtab, aabb:sdf is already mounted on /remote_data

> sshfs aabb:sdf /aabb
mount: according to mtab, aabb:sdf is already mounted on /aabb

There is no mount point about sshfs when I check the /etc/mtab. Here is some infomation:
> ls -la /remote_data/
total 8
drwxr-xr-x  2 root root 4096 Jun 25 15:24 .
drwxr-xr-x 28 root root 4096 Jun 25 15:41 ..

> cat /proc/mounts 
rootfs / rootfs rw 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=16456668k,nr_inodes=4114167,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=3294232k,mode=755 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
none /sys/fs/cgroup tmpfs rw,relatime,size=4k,mode=755 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
none /sys/kernel/debug debugfs rw,relatime 0 0
none /sys/kernel/security securityfs rw,relatime 0 0
none /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
none /run/shm tmpfs rw,nosuid,nodev,relatime 0 0
none /run/user tmpfs rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755 0 0
none /sys/fs/pstore pstore rw,relatime 0 0
/dev/sdb /data ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,name=systemd 0 0

> ps -elf|grep sshfs
0 S root     56552 43957  0  80   0 -  3229 pipe_w 15:44 pts/7    00:00:00 grep --color=auto sshfs

> sshfs -V
SSHFS version 2.5
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a
question about how to use SSHFS rather than a bug report. Could you
please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

As for your question: maybe /etc/mtab is stale? Note that you quoted /proc/mounts, not /etc/mtab

**Comment by sanyechong** [comment]
There is no mount point about sshfs in /etc/mtab either. And I can't umount the dest directory though the program said already mounted:
> sshfs -o remount 10.8.24.3:/remote_data /remote_data/
mount: according to mtab, 10.8.24.3:/remote_data is already mounted on /remote_data

>  umount /remote_data
umount: /remote_data: not mounted

>  cat /etc/mtab |grep sshfs
>
