### ISSUE TITLE
sshfs version 2.10 Device not configured

### ISSUE THREAD

**Issue by chester755** [libfuse/sshfs#135]
Hi all, 

I have been using sshfs 2.5.0 for years without a problem. As I am migrating to a new mac the sshfs start to have this problem as I am trying to mount the machine to my local drive. "Device not configured" error message appears multiple times in the directory where I am trying to mount to. I have uninstalled the 2.5 and reinstalled 2.10 with brew. 
"
SSHFS version 2.10
OSXFUSE 3.8.2
FUSE library version: 2.9.7
fuse: no mount point
"
This is my current setup. Would be good if someone can give me something some advice to proceed. So far the only thing I have tried is to add -o sshfs_debug and the following information is presented:
"
Server version: 3
Extension: posix-rename@openssh.com <1>
Extension: statvfs@openssh.com <2>
Extension: fstatvfs@openssh.com <2>
"

Many thanks in advance.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
