### ISSUE TITLE
Daemonization code doesn't disconnect controlling terminal

### ISSUE THREAD

**Issue by xaizek** [libfuse/sshfs#141]
This looks like a bug to me:

https://github.com/libfuse/sshfs/blob/eac420791c667b038817aaa481c67646e9654e15/sshfs.c#L1032-L1076

Why isn't `setsid()` called after the first `fork()`? By leaving it open daemonized process can still get at least `SIGINT`, which wasn't intended for it.

How to reproduce:

1. `mkdir ~/sshfs-tst`
2. `vim`
3. (in vim) `:!sshfs server: ~/tst`
4. (in vim) `:!read` and hit <kbd>CTRL-C</kbd>

`~/tst` gets unmounted, which shouldn't happen.

Moving `setsid()` should be enough to fix this.

**Comment by Nikratio** [comment]
Thanks for the report! Yes, setsid() should come right after the first fork (at least according to Kerrisk, 2010). Could you provide a patch/pull request?

**Comment by Nikratio** [comment]
(note that I haven't looked at the actual code. Please make sure that reading the password from stdin still works after this change)

**Comment by xaizek** [comment]
No, sorry, building seems to require too much of additional software, I tired to install some, but then it wanted more and more...

**Comment by jose1711** [comment]
i moved ```setsid()``` right after fork like this
```
 	pid = fork();
+	setsid();

```
it works fine in vim but sshfs is unable to read password from stdin (when ssh key is not in place):
```
~ sshfs server: /tmp/mtpoint
read: Connection reset by peer
```

**Comment by xaizek** [comment]
Thanks @jose1711. Realized that I can test this on older version which doesn't require installing anything, but has the same issue. Apparently reading input doesn't work unless final process is a session leader. It seems to work if `setsid()` is just moved out above `if`-statement, just to call it unconditionally.

**Comment by jose1711** [comment]
@xaizek can you please fork and make a testing branch? i am trying to move ```setsid()``` places but sshfs still does not ask for the password. thank you

**Comment by xaizek** [comment]
Just make it look something like this:

 	chdir("/"); 
 	setsid(); 
  
 	if (sshfs.password_stdin) { 
 		int sfd; 
  
 		sfd = open(ptyname, O_RDWR); 

`sshfs.password_stdin` is set on `-o password_stdin`, so I do:

    echo pass | sshfs -o password_stdin server: /tmp/mtpoint

If I do `sshfs server: /tmp/mtpoint`, I do get password request but via some pinentry program with and without changes to the source code.

Do you get password prompt if `setsid()` is left where it is?

**Comment by jose1711** [comment]
with ```setsid()``` right below ```chdir("/");``` the behaviour is as follows:
```
sshfs server: /tmp/mtpoint
read: Connection reset by peer
```
There's no prompt for password or console or in pinentry program.
Sending password via stdin works
```
echo pass | sshfs -o password_stdin server: /tmp/mtpoint
```
With original sourcecode i am getting prompted on console and password is accepted.
```
sshfs server: /tmp/mtpoint
user@server's password: 
# mounted
```

**Comment by xaizek** [comment]
From `man ssh`:

```
SSH_ASKPASS

If ssh needs a passphrase, it will read the passphrase from the current terminal
if it was run from a terminal.  If ssh does not have a terminal associated with
it but DISPLAY and SSH_ASKPASS are set, it will execute the program specified by
SSH_ASKPASS and open an X11 window to read the passphrase. [...]
```

That's probably why I get pinentry.

Since it's `ssh` process which needs a terminal, it's the one that should detach from it afterwards, but it doesn't have such option. Maybe there is no fix for this issue then.
