### ISSUE TITLE
sshfs hangs

### ISSUE THREAD

**Issue by John-Leone** [libfuse/sshfs#143]
Hello,
We encounter this problem on a few servers, most servers on the floor work as expected.
Enter sshfs command:  sshfs -o nonempty xxxxxx@xxxxxxxxx:/tmp /mnt
This command hangs and will not return.
We can see the mount in /proc/mounts and if you enter "df -h" that command will hang too so to clean this up we kill the sshfs PID and fusermount -u /mnt.
But, if we "strace -p <sshfs PID>" the hang will clear and the process works as expected.
Any help will be a big help.

[root@xxxxxxxx ~]# ps -ef |grep sshfs
root     29797 28656  0 13:11 pts/2    00:00:00 sshfs -o nonempty xxxxxx@xxxxxxx:/tmp /mnt
root     29820 28894  0 13:11 pts/8    00:00:00 grep --color=auto sshfs

[root@xxxxxxxx ~]# strace -p 29797
strace: Process 29797 attached
geteuid()                               = 0
lstat("/etc/mtab", {st_mode=S_IFLNK|0777, st_size=17, ...}) = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
getuid()                                = 0
brk(NULL)                               = 0x5621f6f4a000
brk(0x5621f6f70000)                     = 0x5621f6f70000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7efe5e1e7000
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7efe5d2c1280}, {SIG_DFL, [], 0}, 8) = 0
socketpair(AF_LOCAL, SOCK_STREAM, 0, [4, 5]) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7efe5e1d4a10) = 29858
wait4(29858, NULL, 0, NULL)             = 29858
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29858, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
close(5)                                = 0
writev(4, [{"\0\0\0\5\1\0\0\0\3", 9}], 1) = 9
read(4, "\0\0\0\226\2\0\0\0\3", 9)      = 9
read(4, "\0\0\0\30posix-rename@openssh.com\0\0\0\1"..., 145) = 145
writev(4, [{"\0\0\0\r\7\0\0\0\0", 9}, {"\0\0\0\4/tmp", 8}], 2) = 17
read(4, "\0\0\0%i", 5)                  = 5
read(4, "\0\0\0\0\0\0\0\17\0\0\0\0\0\0\20\0\0\0\0\0\0\0\0\0\0\0C\377[\216ax"..., 36) = 36
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7efe5e1d4a10) = 29861
exit_group(0)                           = ?
+++ exited with 0 +++

Thanks,
John

**Comment by John-Leone** [comment]
I straced a working and non-working server and the mount stops at this point.
mount("xxxx@xxxxxxx:/tmp", "/mnt", "fuse.sshfs", MS_NOSUID|MS_NODEV, "fd=3,rootmode=40000,user_id=0,gr"...

Also, I compared both working and non-working servers and found them to be the same in terms of software levels so I'm not sure why one fails and one works.

**Comment by Nikratio** [comment]
Thanks for the report! Could you run with debugging enabled (`-d` option)? In order for the strace output to be useful, please also run in single-threaded, foreground mode (`-f` and `-s`). Thanks!

**Comment by Nikratio** [comment]
Oh, and please confirm that you're using the newest SSHFS (3.x)

**Comment by John-Leone** [comment]
We're using the release that comes with our RedHat distribution.

Red Hat Enterprise Linux Server release 7.2 (Maipo)

[root@xxxxxxxxx tmp]# sshfs -V
SSHFS version 2.5
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19

**Comment by John-Leone** [comment]
Attached is the strace with the options that you requested.

**Comment by John-Leone** [comment]
[sshfs.txt](https://github.com/libfuse/sshfs/files/2501727/sshfs.txt)

**Comment by Nikratio** [comment]
Sorry, I wasn't clear. `-f` and -`d` are SSHFS options, not strace options. They should give you debugging output from SSHFS.

That said, unless you can reproduce the problem with SSHFS 3.x, there is little chance that this will get fixed. SSHFS 2.x only gets critical security fixes at this point.

**Comment by John-Leone** [comment]
Hello,
Thanks for your help.
I will ask Redhat to rebase SSHFS to version 3.x

**Comment by sargenthp** [comment]
I am also running RHEL 7 and sshfs 2.10.1...  I found if I have any rules in auditd...  sshfs will lock up.  Still trying to find a way to fix.

**Comment by Nikratio** [comment]
Closing this for now - please re-open if you can reproduce with version 3.x.

**Comment by sargenthp** [comment]
Gee...  Thanks.  When RH will only provide 2.10.1 and if I try to install
3.x it wants a whole bunch of dependencies that RH does not provide yet.

**Comment by RenaKunisaki** [comment]
This absolutely isn't fixed. sshfs still hangs for me pretty much two or three times per week. Try playing some MP3 files over it for an hour or two, it'll hang almost guaranteed.

SSHFS version 3.7.0
FUSE library version 3.9.3
using FUSE kernel interface version 7.31
fusermount3 version: 3.9.3

**Comment by SeanDS** [comment]
I'm still seeing this with sshfs 2.10.0:

```
sshfs user@server:/remote/path /local/path -o reconnect,ServerAliveInterval=60,ServerAliveCountMax=10 -f -d
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
```

It hangs at the last line there.

**Comment by Arzhakov** [comment]
... It was related to the authorized_keys file on the remote host... ([link](https://unix.stackexchange.com/questions/350904/sshfs-command-does-not-return))
so I ran command

`ssh-copy-id user@server`

after that sshfs started working

**Comment by patrick-tssn** [comment]
@Nikratio Thank you for your wonderful work, Do you have any insight into this issue? I also hang at `utime_omit_ok: 0` my sshfs version is `2.9.9`
