### ISSUE TITLE
OSX feature request: Implement custom URL handler

### ISSUE THREAD

**Issue by briantopping** [libfuse/sshfs#146]
Great project, thanks!

Seems like it could be enhanced a lot on OSX by creating a custom URL handler via `sshfs:`. At that point, one could use the ⌘K in Finder ("Connect to Server") with a URL such as `sshfs://user@host/directory`.

https://superuser.com/questions/548119/how-do-i-configure-custom-url-handlers-on-os-x/959899#959899 has a discussion of this. 

Apologies if this has been asked already. I looked through all the issues and didn't find anything.

**Comment by briantopping** [comment]
Hmm, maybe this belongs in https://github.com/osxfuse/osxfuse

**Comment by Nikratio** [comment]
Thanks for the suggestion! This is the right place to report it, but there has not been a lot of activity regarding MacOS support so unless you you want to work on this yourself, this will probably not be implemented anytime soon.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request. (The issue reporting template has been changed to point this out, but you may have submitted your report before the change).

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
