### ISSUE TITLE
init script is created in /usr/local/etc

### ISSUE THREAD

**Issue by bingbing8** [libfuse/sshfs#147]
I am new to linux and libfuse.
when run sudo ninja install, I see an error. Is the installation fail or this is just an info?
![error](https://user-images.githubusercontent.com/12284203/47595727-953c0480-d936-11e8-9f14-b096c664670e.png)

**Comment by Nikratio** [comment]
It means the init script could not be activated - not quite sure why. You'll have to make sure to manually load the fuse module. Please consult your distributions documentation for details on how to do that.

**Comment by bingbing8** [comment]
Is the issue same as https://github.com/libfuse/libfuse/issues/178?

**Comment by Nikratio** [comment]
Ah, sorry about that. Thanks for following up!

**Comment by yanir3** [comment]
Same thing happened me. Correct me if I'm wrong, but this is an issue when building libfuse, so it belongs in the libfuse repo.

**Comment by Nikratio** [comment]
Right you are, thanks for catching!

**Comment by pbnelson** [comment]
On Ubuntu 19.10, I needed `sudo apt install -y libfuse3-dev`
