### ISSUE TITLE
build and installation of sshfs

### ISSUE THREAD

**Issue by bingbing8** [libfuse/sshfs#148]
I followed [link](https://github.com/libfuse/sshfs). After build and install libfuse, I downloaded  [sshfs-3.5.0](https://github.com/libfuse/sshfs/releases/download/sshfs-3.5.0/sshfs-3.5.0.tar.xz) and extract it under build folder.
but meson does nothing and ninja only install libfuse. I am new to linux, libfuse, and sshfs. What do I miss here?
![sshfs](https://user-images.githubusercontent.com/12284203/47595956-e1d40f80-d937-11e8-8840-03c3e1b48f58.png)

**Comment by Nikratio** [comment]
Thanks for the report - but I'm somewhat at a loss how to answer your question. Why would you extracting sshfs in the build folder, and then expect libfuse to magically install sshfs? Just follow the instructions that come with sshfs. Extract it, create a build folder, run meson, etc.

**Comment by bingbing8** [comment]
Can you make the installation instructions more clear? I don't understand your post too. 

Why would you extracting sshfs in the build folder?
Then where should it extract to?

I don't expect libfuse to magically install sshfs. but I don't know which step is wrong.  The installation instruction [link](https://github.com/libfuse/sshfs) is pretty simple.  Can you tell which step is wrong? I need to fix a bug in our repo to make sshfs work.

1. install libfuse 3.2.6
2. download the latest SSHFS release from https://github.com/libfuse/sshfs/releases
3. extract sshfs-3.5.0 (Where should it extract to?)
4. $ mkdir build; cd build
5. $ meson ..
6 install.
