### ISSUE TITLE
PKG_CHECK chokes in bitbake

### ISSUE THREAD

**Issue by Dan-Azure** [libfuse/sshfs#15]
Hey, there.

There's a line in configure.ac called

PKG_CHECK_MODULES(SSHFS, [fuse >= 2.3 glib-2.0 gthread-2.0])

My bitbake chokes on it and gives a syntax error. I don't know if it's a version compatibility issue or wot, but I find that all my problems vanish if I change the line to

PKG_CHECK_MODULES([SSHFS], [fuse >= 2.3 glib-2.0 gthread-2.0])

Just wanted to mention it.

**Comment by VespertilioAmentis** [comment]
Hello.

I've pulled latest version (via ```git clone```) and this problem occurs again: no extra quoting, syntax error.

Here is an output:

```
 ./configure 
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for library containing dlsym... -ldl
checking OpenSSH version... 5.3 >= 4.4, disabling NODELAY workaround
./configure: line 3796: syntax error near unexpected token `SSHFS,'
./configure: line 3796: `PKG_CHECK_MODULES(SSHFS, fuse >= 2.3 glib-2.0 gthread-2.0)`
```
Quoting this line with square braces doesn't solve an issue.
Getting tag sshfs_2.8 as ZIP archive doesn't solve an issue as well. Did I miss something?
My system is RHEL6, compiler is gcc-4.4.7. If more information is needed I'm glad to share it. Thanks in advance.
