### ISSUE TITLE
password_stdin option doesn't work on some systems

### ISSUE THREAD

**Issue by laffer1** [libfuse/sshfs#16]
The password stdin option is trying to open up /dev/ptmx rather than using a posix standard call like posix_openpt(). This causes problems on FreeBSD because the /dev/ptmx device is not enabled by default and is considered a legacy compatibility option.  While one can manually load the pty compatibility module, it is not quite working as intended. 

As posix_openpt is included in both linux and FreeBSD, it makes sense to do this the standard way.

**Comment by Nikratio** [comment]
Sounds reasonable to me. Is `/dev/tty` also Linux specific? Otherwise opening that might be simpler and/or easier to understand than `posix_openpt`.  

In either case, could you create a patch or pull request?

**Comment by laffer1** [comment]
/dev/tty does exist in FreeBSD. 

I'll work on a patch. It may take a few days as I have other commitments.

**Comment by laffer1** [comment]
Just wanted to leave a quick update on this. 

I have a patch for posix_openpt, but I found a second issue on FreeBSD related to the password feature. I'm going to wait until it's working before submitting.  In Linux, there is an implied behavior of opening a slave pseudo pty that doesn't work the same in FreeBSD. I'm trying to figure out how best to handle it.

**Comment by Nikratio** [comment]
Any progress on this?

**Comment by Nikratio** [comment]
@laffer1 , are you still working on this?

**Comment by laffer1** [comment]
I'm afraid I haven't had time to work on this.

**Comment by Nikratio** [comment]
SSHFS does not have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. When reporting bugs, please understand that unless you are including a pull request or are reporting a critical issue, you will probably not get a response.

To prevent the issue tracker from being flooded with issues that no-one is intending to work on, and to give more visibilty to critical issues that users should be aware of and that most urgently need attention, I will also close most bug reports once they've been inactive for a while.

Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. Unfortunately, SSHFS is a purely volunteer driven project, and at the moment there simply aren't any volunteers.
