### ISSUE TITLE
support of running remote commands just like `ssh -t ` or `sftp -b`

### ISSUE THREAD

**Issue by davxiao** [libfuse/sshfs#161]
I need to run some commands on remote host right after authenticating. The use case is, first I was authenticated as UserA who is a sudoer on remote host, then I run `sudo su - UserB` to become UserB, since UserA is a sudoer, running sudo does not require password. Once I became UserB, sshfs can mount /home/UserB successfully. 

I wonder if above scenario is possible with sshfs.

The following two existing commands do something similar to what I wanted on sshfs:
`ssh -t UserA@remote-host "sudo su - UserB"`
or 
`sftp -b batch-file-which-run-sudo UserA@remote-host`

**Comment by yanir3** [comment]
You can't do that because `sftp` does not have a `sudo` command. That example you've given with `sftp -b` will fail. Why not authenticate as UserB in the first-place?

**Comment by Nikratio** [comment]
yanir3 is right, this is fundamentally impossible. Sorry!
