### ISSUE TITLE
Mount local directory to remote

### ISSUE THREAD

**Issue by sidahmed-malaoui** [libfuse/sshfs#164]
Is it possible to add the feature to mount a local directory to a remote server ? Or does it require too much work ?

**Comment by Nikratio** [comment]
Thanks for the report! I don't think this is something that needs to be added to sshfs. You should be able to do something like

```
ssh <remote-server> -- sshfs <local-system> <mountpoint on remote server>
```

On the other hand, if you cannot SSH from the remote system into the local one, then there is nothing that SSHFS can do about - sorry.
