### ISSUE TITLE
Cannot remove/unlink symlink which has nonexistent target

### ISSUE THREAD

**Issue by jonaslb** [libfuse/sshfs#165]
Executing `ln -s nonexistent_file newlink` and later `rm newlink` or `unlink newlink` works as expected on when executed in any local folder. However, if it is executed in an sshfs mount, the first command exits with an error:

    ln: failed to create symbolic link 'newlink': No such file or directory

But a file is created anyway. It is listed as follows (`ls -la`):

    ??????????  ? ?     ?           ?            ? newlink

But if using `ls -la` on the remote machine, the link is listed correctly:

    lrwxrwxrwx  1 jolub s13       11 28 mar 17:21 newlink -> nonexistent

The link can be removed on the remote via unlink or rm as expected, but it does not work when unlink or rm is executed locally in the mounted folder. In that case unlink (or rm) exits with the following message:

    unlink: cannot unlink 'newlink': No such file or directory

**Comment by jonaslb** [comment]
I should say that I have used the `-o follow_symlinks` option for mounting, but nothing else. I haven't tested it without that option.

**Comment by Nikratio** [comment]
Thanks for the report! This is expected behavior with `-o follow_symlinks` - this means that whenever SSHFS encounters a symlink, it will attempt to follow it instead of acting on the symlink itself.
