### ISSUE TITLE
Bug using vagrant on a fedora 29 workstation

### ISSUE THREAD

**Issue by LittleBoyTimmy** [libfuse/sshfs#167]
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'dev-master' machine. Please report this as a bug:

Internal error. Report this as a bug. Invalid: sshfs

/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:137:in `block in synced_folders'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `each'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `synced_folders'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:19:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_boot_order.rb:78:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_networks.rb:83:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:239:in `action_raw'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:208:in `block in action'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/environment.rb:598:in `lock'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/machine.rb:194:in `action'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by Nikratio** [comment]
Thanks for the report! As far as I can tell this has nothing to do with SSHFS though. I'm also not sure what you're trying to do. Maybe report this against Vagrant (together with whatever command line you are running here)?
