### ISSUE TITLE
Can we upgrade to pcre2

### ISSUE THREAD

**Issue by rverma-nikiai** [libfuse/sshfs#171]
More specifications here https://www.pcre.org/current/doc/html/pcre2.html. Worth upgrading the dependent package.

**Comment by Nikratio** [comment]
Thanks for the suggestion! I'm afraid I don't have time to work on this, but I'm happy to take pull requests.

**Comment by kalvdans** [comment]
The libpcre dependency comes in via glib-2.0. sshfs doesn't make use of any regex engine itself, so this enhancement request should be reported towards glib2 instead of sshfs.

**Comment by Nikratio** [comment]
Thanks for checking! Closing this.
