### ISSUE TITLE
Add support for direct_io

### ISSUE THREAD

**Issue by sunwire** [libfuse/sshfs#172]
Please add support for direct_io mount option

**Comment by sunwire** [comment]
Proposed patch
`diff --git a/sshfs.c b/sshfs.c
index 06a1ef3..a0b40a4 100644
--- a/sshfs.c
+++ b/sshfs.c
@@ -244,6 +244,7 @@ struct sshfs {
        int sync_write;
        int sync_read;
        int sync_readdir;
+  int direct_io;
        int debug;
        int foreground;
        int reconnect;
@@ -408,6 +409,7 @@ static struct fuse_opt sshfs_opts[] = {
        SSHFS_OPT("disable_hardlink",  disable_hardlink, 1),
        SSHFS_OPT("dir_cache=yes", dir_cache, 1),
        SSHFS_OPT("dir_cache=no",  dir_cache, 0),
+       SSHFS_OPT("direct_io",  direct_io, 1),
 
        SSHFS_OPT("-h",         show_help, 1),
        SSHFS_OPT("--help",     show_help, 1),
@@ -2509,6 +2511,9 @@ static int sshfs_open_common(const char *path, mode_t mode,
        if (sshfs.dir_cache)
                wrctr = cache_get_write_ctr();
 
+  if (sshfs.direct_io)
+    fi->direct_io = 1;
+
        if ((fi->flags & O_ACCMODE) == O_RDONLY)
                pflags = SSH_FXF_READ;
        else if((fi->flags & O_ACCMODE) == O_WRONLY)
@@ -3369,6 +3374,7 @@ static void usage(const char *progname)
 "    -o dcache_min_clean_interval=N\n"
 "                           sets the interval for forced cleaning of the\n"
 "                           cache if full (default: 5)\n"
+"    -o direct_io           enable direct i/o\n"
 "    -o workaround=LIST     colon separated list of workarounds\n"
 "             none             no workarounds enabled\n"
 "             [no]rename       fix renaming to existing file (default: off)\n"
`

**Comment by sunwire** [comment]
Proposed patch

[direct_io.txt](https://github.com/libfuse/sshfs/files/3193908/direct_io.txt)

**Comment by frankli0324** [comment]
quite an inspiring PR, u know

**Comment by Nikratio** [comment]
Thanks for the patch and feature suggestion! Could you please submit a pull request instead? If you could include a corresponding entry in Changes.rst and a rationale for the feature (when exactly is it required, and why), that would be helpful.

**Comment by kalvdans** [comment]
The pull request https://github.com/libfuse/sshfs/pull/173 was merged, so I guess this issue can be closed.
