### ISSUE TITLE
Mount Remote Filesystem on Local host

### ISSUE THREAD

**Issue by sree80** [libfuse/sshfs#181]

**Comment by sree80** [comment]
Hi,

I am trying to mount a remote filesystem to my local server. I don't see any example online.
I tried few things and not getting the correct result.

can anyone please share an example with me.

Highly appreciate any info!!!

**Comment by Nikratio** [comment]
From the issue template:

SSHFS does not have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. When reporting bugs, please understand that unless you are including a pull request or are reporting a critical issue, you will probably not get a response.

To prevent the issue tracker from being flooded with issues that no-one is intending to work on, and to give more visibilty to critical issues that users should be aware of and that most urgently need attention, I will also close most bug reports once they've been inactive for a while.

Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. Unfortunately, SSHFS is a purely volunteer driven project,
and at the moment there simply aren't any volunteers.
