### ISSUE TITLE
Impro: umount as root should trigger fusermount3 -u

### ISSUE THREAD

**Issue by Cyborgscode** [libfuse/sshfs#190]
Hi,

if something is mounted via sshfs, you get a nice icon on a desktop, as expected.
If you now try to unmount it via the Desktop, i.e. via a context menu extra "unmount", or via "umount mountpoint" in a user shell, the system denies it with "no privileges"/"Access denied".

As there a umount exes for several filesystems, sshfs could offer a version i.e. "umount.fuse.sshfs" which is just an alias for fuser"mount3 -u mntpoint". 

This is :

- consistent with other filesystems
- userfriendly
- easy

**Comment by Cyborgscode** [comment]
ok, found a PARTLY workaround:

/usr/sbin/umount.fuse.sshfs 
----------------------------------------------
#!/bin/bash

/usr/bin/fusermount3 -u "$1"
----------------------------------------------

It allows a user to execute "umount mntpoint" successfully, but a desktop context-menu umount does not work, yet. 

I will suggest to add this to Fedora.

**Comment by Nikratio** [comment]
Ok, will close this issue then. Thanks for following up!
