### ISSUE TITLE
How i can use VirtualHostKey=yes with sshfs ?

### ISSUE THREAD

**Issue by ZerooCool** [libfuse/sshfs#193]
sshfs -o allow_other,IdentityFile=/home/user/.ssh/id_rsa user@serveur:/home/user/partage /home/localuser/Partage -o nonempty -o VisualHostKey=yes

fuse: unknown option `VisualHostKey=yes'

I have add this conf "VisualHostKey=yes" in :
sudo nano /etc/ssh/ssh_config
and
nano .ssh/config

I can't see any VirtualHostKey with sshfs.

Work for ssh.

**Comment by Jakuje** [comment]
How old `sshfs` do you have? I added `VisualHostKey` keyword to the list of allowed options in `sshfs` more than two years ago.

**Comment by ZerooCool** [comment]
ii  sshfs    2.8-1     amd64        filesystem client based on SSH File Transfer Protocol

ii  libssh-gcrypt-4:amd64     0.8.0~20170825.94fa1e38-1ubuntu0.2      amd64        tiny C SSH library (gcrypt flavor)

ii  libssh2-1:amd64    1.8.0-1     amd64        SSH2 client-side library

ii  openssh-client    1:7.6p1-4ubuntu0.3      amd64   secure shell (SSH) client, for secure access to remote machines

Linux Mint 9.2

**Comment by Nikratio** [comment]
Please update to a newer SSHFS release.
