### ISSUE TITLE
sshfs is reconnecting even when -o reconnect is not specified

### ISSUE THREAD

**Issue by benwbooth** [libfuse/sshfs#201]
Hi,

I'm running sshfs on top of osxfuse on macOS Catalina 10.15.2. I use sshfs to connect to our shared storage at my work. For some reason, sshfs seems to be trying to reconnect multiple times when disconnected, but it fails to reconnect. This is being flagged by my work's IT network, which is resulting in my IP address getting blocked. Here is the command-line I'm using:

```
sshfs "$user@$host:/" /ssh -o idmap=file -o uidfile=uidfile -o gidfile=gidfile -o nomap=ignore -o allow_other,extended_security,noappledouble
```

This is what my IT network's logs say:
```
2020-01-03 17:22:13 nullzero <my ip> syslog@pig.lbl.gov AUTO_DROP: SSH_BRUTEFORCE: ADVISE: HIGH_FAILED_LOGIN: PROTO=SSH USER=<my user> IP=<my ip>
```
where `<my ip>` is my IP address, and `<my user>` is my SSH username. I don't understand why sshfs is trying to reconnect when I did not give it the -o reconnect option. Is there some code in sshfs that causes it to try to reconnect by default? Is there some way to disable it?

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category (and is about an outdated version of SSHFS), so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
