### ISSUE TITLE
Add support for ssh-obfuscation to sshfs

### ISSUE THREAD

**Issue by Coradol** [libfuse/sshfs#203]
Bruce Leidl (@brl) gave a detailed description of the reasons behind his proposal to obfuscate the handshake process of ssh connection. Go over it if you have the time. It's not long and fairly easy to understand. https://github.com/brl/obfuscated-openssh

It would be nice if sshfs would support this way of obfuscation. There are patches for openssh, so maybe it is not that much effort to add a "obfuscation option" for sshfs. https://zinglau.com/projects/ObfuscatedOpenSSHPatches.html

Thank you in advance.

**Comment by Nikratio** [comment]
Could you clarify what exactly you'd like to see done in SSHFS?

As I already said by email, SSHFS internally calls whatever SSH binary is installed on the local and remote machines, and will thus use whatever patches have been applied to them.

**Comment by Coradol** [comment]
To connect to a obfuscaded sshd it is needed to use a keyword to initialize the crypted ssh handshake. The usage on an obfuscation enabled ssh client would then look like: "ssh user@myhost.org -Z obfuscate_keyword". All good, all works.

I would just love to have a way to use it in sshfs with an option like "-o obfuscate_keyword=xxx" and it does the trick inside the sshfs client, like bitvise ssh clinet does. Passing that keyword from sshfs to a patched ssh client does not work (at least for me) and it could be discussed with the maintainer of the openssh patches, but it would simply be nicer to have it supported in sshfs.

If I get it wrong, or it is not duable for sshfs, just close the case. At least I tried it. :-)

Thanks!

**Comment by Nikratio** [comment]
You should be able to pass the option in `~/.ssh/config`. Adding a command line option to SSHFS would be fine to, but you'll need to provide a pull request that implements the feature.

**Comment by Nikratio** [comment]
Closing per my comment above.
