### ISSUE TITLE
upgrade homebrew‘s SHFS to 3.x?

### ISSUE THREAD

**Issue by rexzhang** [libfuse/sshfs#205]

**Comment by Nikratio** [comment]
Thank you for the report! Do you think you could work on this (or do you know someone who could)?

SSHFS is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by boboG** [comment]
Let's see if we can pull this off.

Homebrew currently has sshfs version 2.10 available. So there is a "formula", i.e. a Ruby script that downloads, patches and installs the package. If you can please have a look at https://github.com/Homebrew/homebrew-core/blob/master/Formula/sshfs.rb

Is there any technical reason why sshfs 3.x would not run under macOS?

**Comment by boboG** [comment]
Ok, I had a look at the differences from sshfs 2.10 to 3.70. You switched to the Meson build system of which I know nothing. I created a first Meson-style formula for Homebrew but it needs work (dependencies, ...):

class Newsshfs < Formula
  desc ""
  homepage ""
  url "https://github.com/libfuse/sshfs/releases/download/sshfs-3.7.0/sshfs-3.7.0.tar.xz"
  sha256 "6e7e86831f3066b356e7f16e22f1b8a8f177fda05146f6a5eb821c2fd0541c34"

  depends_on "meson" => :build
  depends_on "ninja" => :build

  def install
    # ENV.deparallelize  # if your formula fails when building in parallel
    mkdir "build" do
      system "meson", *std_meson_args, ".."
      system "ninja", "-v"
      system "ninja", "install", "-v"
    end
  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test newsshfs`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end

**Comment by boboG** [comment]
Tried to build sshfs withjout brew on macOS but I'm stuck. Need help. No fuse3 on macOS. We have "FUSE for macOS": https://github.com/osxfuse/osxfuse

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
