### ISSUE TITLE
Build without root

### ISSUE THREAD

**Issue by kgizdov** [libfuse/sshfs#21]
Hi,

I'm trying to build without root permissions into a local folder. I also have the dependencies and libfuse installed in a local folder. I pass these like this:

    ./configure --prefix=$HOME/local/path --libdir=$HOME/local/path/lib --bindir=$HOME/local/path/bin --includedir=$HOME/local/path/include

but I always get the error that fuse is not installed.
Is the build environment missing the option for this or am I missing something?

Thanks.

**Comment by Nikratio** [comment]
You are specifying installation directories, not directories to search for FUSE. Best solution is to make sure that `pkg-config --cflags fuse` and `pkg-config --libs fuse` outputs the right things. Alternatively, specify paths etc using `CFLAGS`, see the `./configure --help` output.

That said, this is not a bug in sshfs. Please use the fuse mailing list for such questions.
