### ISSUE TITLE
Can it run in Window 10 ?

### ISSUE THREAD

**Issue by elishateng** [libfuse/sshfs#214]
PLEASE READ BEFORE REPORTING AN ISSUE

SSHFS does not have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. When reporting bugs, please understand that unless you are including a pull request or are reporting a critical issue, you will probably not get a response.

To prevent the issue tracker from being flooded with issues that no-one is intending to work on, and to give more visibilty to critical issues that users should be aware of and that most urgently need attention, I will also close most bug reports once they've been inactive for a while.

Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. Unfortunately, SSHFS is a purely volunteer driven project,
and at the moment there simply aren't any volunteers.

**Comment by a8underscore** [comment]
no

**Comment by nbfalcon** [comment]
From what I could gather, apparently yes, using WSL2: (https://superuser.com/a/1544327).
There was an issue with explorer not being able to browse mounted sshfs filesystems (see [here](https://github.com/microsoft/WSL/issues/4172)). However, it seems to have been fixed and is working now (https://github.com/microsoft/WSL/issues/4172).

Disclaimer: please note that I do not use Windows, but hope that my answer, based solely on research, would be of use to someone.

**Comment by zhangn1985** [comment]
please use: https://github.com/billziss-gh/sshfs-win for windows.
