### ISSUE TITLE
"No such file or directory" after Fuse update

### ISSUE THREAD

**Issue by lawrencebensaid** [libfuse/sshfs#217]
To be honest I'm not sure if this issue should be posted here but here goes:

Today I reinstalled Fuse and I got this message when trying to connect:
```
$ sshfs root@10.0.0.101:/ /Volumes/node1 -o volname=node1
/Volumes/node1: No such file or directory
```

Does anyone know what might be wrong?
Thanks in advance!

**Comment by Nikratio** [comment]
Probably the directory `/Volumes/node1` does not exist?

**Comment by lawrencebensaid** [comment]
Well yes, obviously hahaha. But it did not do that before. And when I create a folder there before connecting I get: `remote host has disconnected`

**Comment by Nikratio** [comment]
What do you mean with "there"? Your commandline tells sshfs to mount the remote root directory `/` to the local directory `/Volumes/node1`  - which does not exist.

**Comment by lawrencebensaid** [comment]
@Nikratio `there` is referring to `/Volumes/node1`. My point is that when I create the folder `/Volumes/node1` it still does not work because I get the following message: `remote host has disconnected`. Also what I am trying to say is that prior to updating Fuse it was not necessary to create a folder at the mount location.

**Comment by Nikratio** [comment]
I'm sorry, I don't think that SSHFS ever created the local mountpoint if it did not exist. And FUSE certainly did not either.

Please confirm that you're indeed using the same SSHFS as this GitHub project is about.
