### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by metayan** [libfuse/sshfs#226]
```
leaks 88335
Process:         sshfs [88335]
Path:            /usr/local/Cellar/sshfs/2.10_2/bin/sshfs
Load Address:    0x104458000
Identifier:      sshfs
Version:         ???
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2020-08-31 13:39:24.150 +0200
Launch Time:     2020-08-30 22:02:54.335 +0200
OS Version:      Mac OS X 10.13.6 (17G14019)
Report Version:  7
Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
Analysis Tool Version:  Xcode 10.1 (10B61)

Physical footprint:         9.3G
Physical footprint (peak):  9.3G
----

leaks Report Version: 4.0
Process 88335: 5716785 nodes malloced for 9843305 KB
Process 88335: 5481391 leaks for 9696202144 total leaked bytes.
```
Same behaviour as described in
https://github.com/osxfuse/sshfs/issues/43

Might have a thorough look at what is causing it later.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category (in particular, it applies to a very old version of SSHFS), so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
