### ISSUE TITLE
Treating "~/" directory as a directory named "~" instead of home folder

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [libfuse/sshfs#229]
If I mount to a directory somewhere under my home directory using ~, it recognize it as a folder named ~ under current directory instead of the home directory.

**Comment by Wuestengecko** [comment]
Expanding the `~/` prefix is the shell's job, not sshfs'. Can you provide the full command line that you're invoking?

**Comment by 2young-2simple-sometimes-naive** [comment]
> Expanding the `~/` prefix is the shell's job, not sshfs'. Can you provide the full command line that you're invoking?

`sshfs xxx@xxx.xxx:/home/xxx/scratch ~/mounted -o volname=MARCC,auto_cache,defer_permissions,allow_other,noapplexattr,noappledouble
`
This will make a directiry ~ under current directory and mount in "mounted" under ~

`sshfs xxx@xxx.xxx:/home/xxx/scratch /Users/xxx/Documents/mounted -o volname=MARCC,auto_cache,defer_permissions,allow_other,noapplexattr,noappledouble
`

This works OK.

**Comment by Wuestengecko** [comment]
The command looks good to me. Which shell are you using? Can you use the `~/` in other commands or is it broken there as well? What do `alias sshfs` and `which sshfs` say?

**Comment by 2young-2simple-sometimes-naive** [comment]
I will close this thread as I just realized it is actually the problem of the shell I am using, not sshfs.
