### ISSUE TITLE
Slow directory listing on macOS

### ISSUE THREAD

**Issue by jonashaag** [libfuse/sshfs#230]
Problem: Listing directories on macOS (eg. using Finder) is very slow when the directory has lots of files.

I am willing to spend some time fixing this if it is reasonably easy.

Debug output when waiting for directory listing to finish: LOTS of these:

```
LOOKUP <folder>._<file1>
getattr <folder>._<file1>
unique: 2335, opcode: ACCESS (34), nodeid: 12644, insize: 48, pid: 377
access <folder><file1> 04
   unique: 2335, success, outsize: 16
unique: 2332, opcode: ACCESS (34), nodeid: 12644, insize: 48, pid: 377
access <folder><file1> 01
   unique: 2332, error: -13 (Permission denied), outsize: 16
unique: 2336, opcode: GETXATTR (22), nodeid: 12644, insize: 77, pid: 377
getxattr <folder><file1> com.apple.FinderInfo 32 0
   unique: 2336, error: -45 (Operation not supported), outsize: 16
   unique: 2334, error: -2 (No such file or directory), outsize: 16
unique: 550, opcode: LOOKUP (1), nodeid: 85, insize: 93, pid: 377
```

So I guess it's simply requesting the files one by one which is very slow.

**Comment by Nikratio** [comment]
Your best bet is to work on OSXFUSE and extend it to support the libfuse 3.x API. That way, you will be able to use SSHFS 3.x, which comes with readdirplus() support that should help.

https://github.com/osxfuse/osxfuse/issues/390
