### ISSUE TITLE
*** Error in `sshfs': double free or corruption (fasttop): 0xb51004b8 ***

### ISSUE THREAD

**Issue by linuxdeveloper** [libfuse/sshfs#231]
Crash in sshfs<1083>, thread 1230, signal 6, pc b6c90d84, lr b6c92498

sshfs crashed with this error : *** Error in `sshfs': double free or corruption (fasttop): 0xb51004b8 ***

Here is the coredump : 
[task info]
  process sshfs<1083> received signum 6 in thread 1230
  cmdline was 'sshfs -f -o rw,noatime,noexec,nosuid,nodev,port=22,idmap=user,allow_other,recon'
  uid/gid: 6000/7000
  utime/stime: 0.0/0.0
  cutime/cstime: 0.0/0.0
  state: D
  nr threads: 5

[memory maps]
00010000-0001f000 r-xp 00000000 00:0e 328        /usr/bin/sshfs
0002e000-0002f000 rw-p 0000e000 00:0e 328        /usr/bin/sshfs
009a3000-009c4000 rw-p 00000000 00:00 0          [heap]
b4900000-b4901000 ---p 00000000 00:00 0 
b4901000-b5100000 rw-p 00000000 00:00 0          [stack:1468]
b5100000-b5121000 rw-p 00000000 00:00 0 
b5121000-b5200000 ---p 00000000 00:00 0 
b52b2000-b52ce000 r-xp 00000000 00:0e 3621       /lib/libgcc_s.so.1
b52ce000-b52dd000 ---p 0001c000 00:0e 3621       /lib/libgcc_s.so.1
b52dd000-b52de000 rw-p 0001b000 00:0e 3621       /lib/libgcc_s.so.1
b52de000-b5300000 rw-p 00000000 00:00 0 
b5300000-b5301000 ---p 00000000 00:00 0 
b5301000-b5b00000 rw-p 00000000 00:00 0          [stack:1232]
b5b00000-b5b01000 ---p 00000000 00:00 0 
b5b01000-b6300000 rw-p 00000000 00:00 0          [stack:1231]
b6300000-b6321000 rw-p 00000000 00:00 0 
b6321000-b6400000 ---p 00000000 00:00 0 
b640e000-b6430000 rw-p 00000000 00:00 0 
b6430000-b6431000 ---p 00000000 00:00 0 
b6431000-b6c52000 rw-p 00000000 00:00 0          [stack:1230]
b6c52000-b6c54000 r-xp 00000000 00:0e 3045       /lib/libdl-glibc_2.23_tp_16_g396d426.so
b6c54000-b6c63000 ---p 00002000 00:0e 3045       /lib/libdl-glibc_2.23_tp_16_g396d426.so
b6c63000-b6c64000 r--p 00001000 00:0e 3045       /lib/libdl-glibc_2.23_tp_16_g396d426.so
b6c64000-b6c65000 rw-p 00002000 00:0e 3045       /lib/libdl-glibc_2.23_tp_16_g396d426.so
b6c65000-b6d94000 r-xp 00000000 00:0e 3475       /lib/libc-glibc_2.23_tp_16_g396d426.so
b6d94000-b6da3000 ---p 0012f000 00:0e 3475       /lib/libc-glibc_2.23_tp_16_g396d426.so
b6da3000-b6da5000 r--p 0012e000 00:0e 3475       /lib/libc-glibc_2.23_tp_16_g396d426.so
b6da5000-b6da6000 rw-p 00130000 00:0e 3475       /lib/libc-glibc_2.23_tp_16_g396d426.so
b6da6000-b6da9000 rw-p 00000000 00:00 0 
b6da9000-b6dbf000 r-xp 00000000 00:0e 4145       /lib/libpthread-glibc_2.23_tp_16_g396d426.so
b6dbf000-b6dcf000 ---p 00016000 00:0e 4145       /lib/libpthread-glibc_2.23_tp_16_g396d426.so
b6dcf000-b6dd0000 r--p 00016000 00:0e 4145       /lib/libpthread-glibc_2.23_tp_16_g396d426.so
b6dd0000-b6dd1000 rw-p 00017000 00:0e 4145       /lib/libpthread-glibc_2.23_tp_16_g396d426.so
b6dd1000-b6dd3000 rw-p 00000000 00:00 0 
b6dd3000-b6f4f000 r-xp 00000000 00:0e 1383       /usr/lib/libglib-2.0.so.0.4600.2
b6f4f000-b6f5e000 ---p 0017c000 00:0e 1383       /usr/lib/libglib-2.0.so.0.4600.2
b6f5e000-b6f60000 rw-p 0017b000 00:0e 1383       /usr/lib/libglib-2.0.so.0.4600.2
b6f60000-b6f61000 r-xp 00000000 00:0e 1484       /usr/lib/libgthread-2.0.so.0.4600.2
b6f61000-b6f70000 ---p 00001000 00:0e 1484       /usr/lib/libgthread-2.0.so.0.4600.2
b6f70000-b6f71000 rw-p 00000000 00:0e 1484       /usr/lib/libgthread-2.0.so.0.4600.2
b6f71000-b6f92000 r-xp 00000000 00:0e 1290       /usr/lib/libfuse.so.2.9.4
b6f92000-b6fa2000 ---p 00021000 00:0e 1290       /usr/lib/libfuse.so.2.9.4
b6fa2000-b6fab000 rw-p 00021000 00:0e 1290       /usr/lib/libfuse.so.2.9.4
b6fab000-b6fcb000 r-xp 00000000 00:0e 3449       /lib/ld-glibc_2.23_tp_16_g396d426.so
b6fd5000-b6fda000 rw-p 00000000 00:00 0 
b6fda000-b6fdb000 r--p 0001f000 00:0e 3449       /lib/ld-glibc_2.23_tp_16_g396d426.so
b6fdb000-b6fdc000 rw-p 00020000 00:0e 3449       /lib/ld-glibc_2.23_tp_16_g396d426.so
beee2000-bef03000 rw-p 00000000 00:00 0          [stack]
beffb000-beffc000 r-xp 00000000 00:00 0          [sigpage]
ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]

[registers]
  r0 00000000  r1 000004ce  r2 00000006  r3 b6c2f930  
  r4 00000002  r5 b6c2f470  r6 b6da5ef0  r7 0000010c  
  r8 00000001  r9 00000002  r10 00000005  fp b6c2ea78  
  ip 00000128  sp b6c2e82c  lr b6c92498  pc b6c90d84  
  cpsr 200e0010  orig_r0 0000043b  

[call trace]
  unavailable

[auxiliary vector]
  AT_HWCAP = 0x1fb0d6 (2076886)
  AT_PAGESZ = 0x1000 (4096)
  AT_CLKTCK = 0x64 (100)
  AT_PHDR = 0x10034 (65588)
  AT_PHENT = 0x20 (32)
  AT_PHNUM = 0x8 (8)
  AT_BASE = 0xb6fab000 (-1225084928)
  AT_FLAGS = 0x0 (0)
  AT_ENTRY = 0x13064 (77924)
  AT_UID = 0x1770 (6000)
  AT_EUID = 0x1770 (6000)
  AT_GID = 0x1b58 (7000)
  AT_EGID = 0x1b58 (7000)
  AT_SECURE = 0x0 (0)
  AT_RANDOM = 0xbef02d6e (-1091555986)
   = 0x0 (0)
  AT_EXECFN = 0xbef02fed (-1091555347)
  AT_PLATFORM = 0xbef02d7e (-1091555970)

[last stack frame]
  unavailable

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category (in particular it lacks instructions to reproduce the problem), so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
