### ISSUE TITLE
Don't support macos big sur

### ISSUE THREAD

**Issue by F3ngdw** [libfuse/sshfs#234]
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid there is nothing on the SSHFS side that can be done here. Someone needs to develop a libfuse for MacOS Big Sur.

**Comment by bfleischer** [comment]
FUSE for macOS supports Big Sur. Please raise the issue in the osxfuse issue tracker.
