### ISSUE TITLE
SSH's PubkeyAuthentication option not passed through

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [libfuse/sshfs#237]
stderr:

```
fuse: unknown option `PubkeyAuthentication=no'
```

It's a ssh option.

**Comment by ElectricRCAircraftGuy** [comment]
Please see my detailed instructions here: https://github.com/ElectricRCAircraftGuy/sshfs/tree/update_readme#sshkeygen under the section **(Optional, but recommended) test your new sshfs executable. [This also includes detailed notes about ssh key generation and setup].** Do these instructions fix this?

**Comment by ElectricRCAircraftGuy** [comment]
Nevermind. I think I was just confused. These things seem to be unrelated. Here's my attempt:

```
$ sshfs -o PubkeyAuthentication=no 10.0.0.1: ~/mnt/temp
fuse: unknown option(s): `-o PubkeyAuthentication=no'
```

**Comment by Nikratio** [comment]
I doubt that this worked in the past, SSHFS has a whitelist of options that can be safely passed through: https://github.com/libfuse/sshfs/blob/master/sshfs.c#L389

Pull requests welcome.

**Comment by dkebler** [comment]
sady focal packages don't keep up (at 3.6) and libfuse is only at 3.9.   I couldn't find a ppa for sshfs/libfuse  any way to get builds on current releases without building myself?

**Comment by dkebler** [comment]
sady focal packages don't keep up (at 3.6) and libfuse is only at 3.9.   I couldn't find a ppa for sshfs/libfuse  any way to get builds on current releases without building myself? 

Ok so I tried

I loaded fuse3  
```
fuse3:
  Installed: 3.9.0-2
  Candidate: 3.9.0-2
  Version table:
 *** 3.9.0-2 500
        500 http://mirrors.cat.pdx.edu/ubuntu focal/universe amd64 Packages
        100 /var/lib/dpkg/status
```
rats!  why am I getting this error
`meson.build:47:0: ERROR: Dependency "fuse3" not found, tried pkgconfig and cmake`
