### ISSUE TITLE
Does not work anymore after windows update

### ISSUE THREAD

**Issue by jayjupdhig** [libfuse/sshfs#241]
sshfs version: 3.5.20024
winfsp version: 1.7.20172
windows version: 10 Pro x64 with most current updates on 15-01-2021

Problem:

![111](https://user-images.githubusercontent.com/42765391/104747996-7d3c3f80-5751-11eb-82db-a4e3bd49d13f.jpg)

Is that a winfsp or a sshfs issue after the windows update from today?

How to solve? Is there a new version with the necessary compatibility or do i need to wait for it?

Thank you very much for your feedbacks! :-)

**Comment by Nikratio** [comment]
I don't think you're in the right place. The SSHFS project that this is about has never supported Windows.
