### ISSUE TITLE
Fails to build on macOS

### ISSUE THREAD

**Issue by grischard** [libfuse/sshfs#248]
**How to reproduce:**

- Install macfuse from https://osxfuse.github.io or through `brew install macfuse`
- Install build dependencies (for example through `brew install meson ninja pkg-config glib`
- Download the latest sshfs release
- `mkdir build && cd build`
- `meson ..`

**Expected result:**

sshfs can be built

**Actual results:**

Fails to build, fails to find 'fuse3' (see log)

**Discussion:**

`pkg-config --list-all` finds the other packages installed through homebrew.

`/usr/local/include/fuse` contains:
fuse.h                  fuse_common.h           fuse_common_compat.h    fuse_compat.h           fuse_lowlevel.h         fuse_lowlevel_compat.h  fuse_opt.h

**Comment by Nikratio** [comment]
That's because MacFUSE does not provide fuse3. If you want to build SSHFS 3.x on Mac, you first need to get a libfuse3 implementation for Mac from somewhere.

**Comment by grischard** [comment]
Ah, it's linked to https://github.com/osxfuse/osxfuse/issues/390 then.

The readme led me to believe that sshfs could be built on macOS - should it be amended to say that the latest version currently can't?
