### ISSUE TITLE
suspending the system fails if an sshfs mount being accessed

### ISSUE THREAD

**Issue by chen-chan** [libfuse/sshfs#25]
Same as [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=565229) and [this](https://bugs.launchpad.net/ubuntu/+source/sshfs-fuse/+bug/388419) bug I think. How I can reliably reproduce:
- Open a file manager and go to an sshfs directory with lots of images or videos.
- While thumbnails are being generated, suspend the computer.
- Result: screen locks, instead of suspending, system freezes entirely for ~20 seconds, screen can then  be unlocked (and with some apps, the entire WiFi device completely disappears from the system, that's another funny side effect).

This makes using sshfs on laptop not very viable.

**Comment by Nikratio** [comment]
Sorry, I have no idea how to debug this... I know very little about how the kernel suspend process works.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, with the
current state of affairs it's unlikely that anyone is going to be able  to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database
of known/potential issues).
