### ISSUE TITLE
SSHFS does not compile: fuse3 not found

### ISSUE THREAD

**Issue by freebrowser1** [libfuse/sshfs#251]
Running macOS 10.16.3 Big Sur and Xcode 12.5 I tried compiling this package by running this:

`userpc:~/scratch/sshfs-3.7.1/build % meson ..
The Meson build system
Version: 0.58.0
Source dir: /Users/user/Downloads/sshfs-3.7.1
Build dir: /Users/user/Downloads/sshfs-3.7.1/build
Build type: native build
Project name: sshfs
Project version: 3.7.1
C compiler for the host machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.9)")
C linker for the host machine: cc ld64 650.9
Host machine cpu family: x86_64
Host machine cpu: x86_64
../meson.build:8: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
../meson.build:8: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Program rst2man rst2man.py found: NO
Configuring config.h using configuration
Found pkg-config: /Users/user/homebrew/bin/pkg-config (0.29.2)
Found CMake: /Users/user/homebrew/bin/cmake (3.20.2)
Run-time dependency fuse3 found: NO (tried pkgconfig, framework and cmake)

../meson.build:47:0: ERROR: Dependency "fuse3" not found, tried pkgconfig, framework and cmake

A full log can be found at /Users/user/Downloads/sshfs-3.7.1/build/meson-logs/meson-log.txt
userpc:~/scratch/sshfs-3.7.1/build % brew install fuse3`

And installing fuse3 with brew also failed. 
I run macFuse 4.10.

**Comment by Nikratio** [comment]
Thanks for the report. As the error message said, you need fuse3 for SSHFS 3.x. This is not a bug - at least not in SSHFS.

**Comment by freebrowser1** [comment]
But how can I get fuse3 ?
I cannot install it using Homebrew.

**Comment by Nikratio** [comment]
I don't know, I am not using MacOS and I have no idea what Homebrew is. All I know is that SSHFS depends on FUSE3. If there is no FUSE3 for MacOS, then SSHFS won't work under MacOS.

**Comment by Nikratio** [comment]
Looks like there is a pending feature request for OSXFUSE, https://github.com/osxfuse/osxfuse/issues/390

**Comment by freebrowser1** [comment]
Well, OSXFuse works fine on my Mac and Homebrew as well.
So it is an issue in sshfs.

Can I get a binary of sshfs ?

**Comment by freebrowser1** [comment]
I could not find this ticket anymore, hence I added a new one #253, but you closed it correctly. Sorry.

But where should I report this error as it is not an SSHFS error ?
It is not a Homebrew error as well.
Maybe Fuse ? Because Fuse works correctly.

**Comment by steamboatid** [comment]
you need to install libfuse development package first
