### ISSUE TITLE
Load key "~/.ssh/id_rsa": invalid format

### ISSUE THREAD

**Issue by ramaxa9** [libfuse/sshfs#266]
When im trying to mount i end up with this error:
```
$: sudo sshfs -o debug,allow_other,default_permissions,IdentityFile=/~/.ssh/id_rsa mro@xxxx:/ ~/xxx                                             
SSHFS version 3.7.2
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oIdentityFile=/~/.ssh/id_rsa> <-2> <mro@xxxx> <-s> <sftp>
Load key "/~.ssh/id_rsa": invalid format
mro@xxxx: Permission denied (publickey).
read: Connection reset by peer
```

the key is RSA2 2048bit (with the passphrase, if this is important)

**Comment by loganwoodxyz** [comment]
I guarantee you don’t have a directory called `/~/.ssh`

**Comment by ramaxa9** [comment]
That not the case, the path is correct. Human error when writing

**Comment by loganwoodxyz** [comment]
> That not the case, the path is correct. Human error when writing the message
> 
> I will check once again

What’s the update on this?

**Comment by Nikratio** [comment]
Closing this for now lacking further information.
