### ISSUE TITLE
Can't display german Umlaute

### ISSUE THREAD

**Issue by Machion** [libfuse/sshfs#268]
I am using sshfs on Manjaro Linux connecting to an university server and file/folder names containing german Umlaute (ä, ö, ü) are replaced by an "?". 
Is this a bug of sshfs or wrong settings at the local or server side?

**Comment by Nikratio** [comment]
Thanks for the report! I'm afraid this is unrelated to SSHFS, SSHFS simply forwards the bytes it gets, without interpretation.
