### ISSUE TITLE
Win-SSHFS don't allow me to point a remote /mnt/foo dir

### ISSUE THREAD

**Issue by lucpierson** [libfuse/sshfs#272]
Hello
I've connected  with no problem to a remote fedora (/mnt/foo) folder with 
    1) a fedora sshfs client, 
    2) a macos sshfs (https://osxfuse.github.io) client 

but with this windows client (using of course, sames credentials), that won't work (the folder you entered is invalid) 
   I can access to the user home, no problem, but not to that /mnt/foo folder

Any idea ?
Thanks
Luc

**Comment by hboetes** [comment]
I think you should report that problem over here: https://github.com/billziss-gh/sshfs-win
if it does not exist already.

**Comment by Nikratio** [comment]
I think you got the wrong project, this one is not providing any windows sshfs client.
