### ISSUE TITLE
Slow Performance with Debian 11

### ISSUE THREAD

**Issue by tobias992** [libfuse/sshfs#275]
Hello,

i have 2 new installed servers - one with Debian 10 and one with Debian 11.

Version Debian 10:
SSHFS version 2.10.0
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19

Version Debian 11:
SSHFS version 3.7.1
FUSE library version 3.10.3
using FUSE kernel interface version 7.31
fusermount3 version: 3.10.3

I tested my 1G connection with iperf3 -> full speed

With Debian 10 i have very good write/read speed with sshfs (110 MB/s)

But with Debian 11 i only have 15-20 MB/s.

I checked all configs -> the same
Mountpoints -> the same
Command to use sshfs -> the same

I don't know why Debian 11 performs so bad with sshfs. Do you have any ideas?

**Comment by manwe** [comment]
I'm experiencing more or less the same. 
New debian 11 server and I get 100mbps while using scp/sftp/rsync I gte over 400 mbps. 
Tried every mount options with no luck
Tried oxfs as replacement and achieved almost 300 mbps.
I'll test not with debian 10, didn't think about it before.

**Comment by Nikratio** [comment]
Thanks for taking the time to report this issue!

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

I will leave this issue open for a little while just in case, but if there's no further activity I'll probably close this issue to prevent the tracker from overflowing with stale issues. I hope you understand.

This is just to calibrate expectations. I am grateful that you took the time and effort to report this! Who knows, maybe someone will pick it up after all :-).

**Comment by manwe** [comment]
Thank you for your time mantaining this!
