### ISSUE TITLE
sshfs-mounts created during startup/boottime get unmounted at login time

### ISSUE THREAD

**Issue by DudeMcGee** [libfuse/sshfs#276]
I have created a systemd service which starts a script doing sshfs mounts. These mounts do exist, the script puts out directory listings after mounting a share. At the moment I login to the machine, these mounts are gone, as if someone had unmounted them all.

Any idea which process does this? Or whatelse could be the reason for this phenomenon?

**Comment by Nikratio** [comment]
SHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
