### ISSUE TITLE
Disconnects randomly

### ISSUE THREAD

**Issue by ironlion27** [libfuse/sshfs#29]
Running docker image to serve Plex Media Server with a volume being a mount location that is mounted via Sshfs.  The mount is unmounted at random intervals for some reason making the docker container useless.  Why would the Sshfs be u mounting without being invoked and how do I keep it mounted.  I added it to /etc/fstab but hasn't stopped the random unmounting.

**Comment by Nikratio** [comment]
Thanks for the report! Could you provide some more information? For example:

Is there anything in the kernel logs? Is this mountpoint clean afterwards, or do you get a "Transport not connected" error when accessing it? What's the exit status of the sshfs process? What are the intervals at which this is happening?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
