### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by chenrui333** [libfuse/sshfs#292]
👋 looks like the project [seems back to life again](https://github.com/libfuse/sshfs/commit/551752c3a57def3c49ced08a6246fcfdd8640e7a)? I wonder what would be the project status now, is it still maintained? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/159266

**Comment by chenrui333** [comment]
cc @h4sh5 @Nikratio  thoughts?

**Comment by Nikratio** [comment]
The readme file is accurate.
