### ISSUE TITLE
Incorrect mapping from local storage to remote storage

### ISSUE THREAD

**Issue by fungtion** [libfuse/sshfs#298]
Hi, I install sshfs on local machine A, and I create a link to /data in my home. Then I use sshfs to mapping the remote machine B to machine A, and B also has a link to its /data in its home. When I open the /data of B, I find it actually points to /data of A, can you help me to get the correct mapping?

**Comment by h4sh5** [comment]
Can you describe the commands you ran on each machine please?

**Comment by fungtion** [comment]
on machine A:
- create link to `/data` in home directory: `cd ~ && ln -s /data`
- mount machine B to `/mnt/b`: `sudo mkdir /mnt/b && sudo sshfs -o allow_other,default_permissions user_B@ip_B:/home/user_B /mnt/b`
- create link to `/mnt/b` in home directory: `sudo chmod 777 /mnt/b && cd ~ && ln -s /mnt/b`

On machine B:
- create link to `/data` in home directory: `cd ~ && ln -s /data`

Then when I open `~/b/` on A, I find this folder is actually points to `/data` of A instead of B

**Comment by bfleischer** [comment]
In case you are on macOS, the mount option `jail_symlinks` might be what you are looking for. When specifying `jail_symlinks`, all absolute symlinks on the mounted volume are prefixed with the mount point of the volume.

**Comment by fungtion** [comment]
@bfleischer Thanks, I'm on Ubuntu, after I add `-o follow_symlinks`, it works
