### ISSUE TITLE
Brew install not working on MacOS

### ISSUE THREAD

**Issue by lodenrogue** [libfuse/sshfs#308]
brew install sshfs gives this error: 

```
libfuse: Linux is required for this software
```

Full output of the brew install command:

```
==> Downloading https://formulae.brew.sh/api/formula.jws.json
##O=#    #                                                                                                                                                        
==> Downloading https://formulae.brew.sh/api/cask.jws.json

sshfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: sshfs: Unsatisfied requirements failed this build.
```

I'm on M2 Sonoma.

**Comment by kslattery** [comment]
I ran into this same issue today. It's a homebrew problem, though, not a sshfs issue. Here's the commit to homebrew that added the `depends_on :linux` that's leading to our error message:
https://github.com/Homebrew/homebrew-core/commit/c5ffc556e7610bc87370584f051d849e844e0087

There used to be a message describing their reasoning (the formula being unusable without  closed-source macFUSE), but that was also removed with this commit. Here's the text that used to be shown when attempting to install on MacOS:
```
       The reasons for disabling this formula can be found here:
          https://github.com/Homebrew/homebrew-core/pull/64491
        An external tap may provide a replacement formula. See:
          https://docs.brew.sh/Interesting-Taps-and-Forks
```

**Comment by kslattery** [comment]
@lodenrogue I followed the "Interesting Taps and Forks" link from that deleted text and there's a link to gromgit/fuse. Following that to https://github.com/gromgit/homebrew-fuse, I followed the instructions to install with this command:
```brew install gromgit/fuse/sshfs-mac ```
and it worked great.

**Comment by lodenrogue** [comment]
Thanks I'll check it out @kslattery

**Comment by IgorKha** [comment]
Perhaps it would be easier for everyone if the releases included pre-compiled binary files as well? Similar to what the sshs team has done, for example: https://github.com/quantumsheep/sshs/releases/tag/4.4.1

**Comment by bfleischer** [comment]
A precompiled universal binary (Apple Silicon and Intel) of SSHFS 2.10 is available on https://macfuse.io and https://github.com/libfuse/sshfs/releases/tag/sshfs-2.10. 

As of writing this, version 2.10 is the latest version of SSHFS that will run on macOS. SSHFS 3.x requires libfuse 3 which has not been ported to macOS. yet

**Comment by excavator-matt** [comment]
Thanks for posting. I have the same issue.

 @bfleischer seems to be correct. There is a raised [issue for this on libefuse](https://github.com/libfuse/libfuse/issues/1075), but unfortunately there doesn't seem to be a clear path forward. Although I work as a software engineer, I must embarrassingly admit that I don't follow the discussion.

Let me try the suggested workaround with macfuse and share the result.

**Comment by SoCuul** [comment]
> Thanks for posting. I have the same issue on M4 Pro and macOS 15.3 Sequoia.
> 
> [@bfleischer](https://github.com/bfleischer) seems to be correct. There is a raised [issue for this on libefuse](https://github.com/libfuse/libfuse/issues/1075), but unfortunately there doesn't seem to be a clear path forward. Although I work as a software engineer, I must embarrassingly admit that I don't follow the discussion.
> 
> The workaround of trying to install macfuse seems to require the enablement of "system extension". Is this truly safe?

For context, it's as safe as installing a kernel-mode driver on Windows. The difference is on macOS the ability to install non-apple kernel-mode drivers requires you to explicitly allow it by following a few steps.

**Comment by minhnguyen1908** [comment]
I'm new to this stuff. After read through the post I'm still don't know if I can still install macFUSE via Homebrew then install sshfs also via Homebrew too. Or I need to install from .dmg file? Could someone help me with it!

I installed macFUSE via Homebrew already, and then tried to install sshfs but received this output:

```zsh
➜  mkdocs brew install sshfs
==> Fetching downloads for: sshfs
sshfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: sshfs: Unsatisfied requirements failed this build.
==> No outdated dependents to upgrade!
```

This is my macFUSE version:

```
➜  mkdocs brew list macfuse
==> Pkg
Extras/macFUSE 4.10.2.pkg (Pkg)
==> Postflight Block
postflight (Postflight Block)
```

**Comment by kslattery** [comment]
@minhnguyen1908  bfleischer said above that MacFuse 4.10+ ships with sshfs. I don't know if the Homebrew folks keep sshfs bundled, though. I do know that the MacFuse install page https://github.com/macfuse/macfuse/wiki/Getting-Started says that they do not control the version offered in package managers (like Homebrew), and they suggest that you download the binaries directly from https://macfuse.io/ or https://github.com/macfuse/macfuse/releases .
You might just try running MacFuse as-is - maybe Homebrew has been updated to use the MacFuse-included sshfs (which seems unlikely given the reasons they had for removing it in the first place). If it doesn't work, though, I'd suggest uninstalling the brew version of MacFuse and installing the version offered on macfuse.io.

**Comment by karlacio** [comment]
From  [github.com/macos-fuse-t](https://github.com/macos-fuse-t/fuse-t#installing-from-brew)

> brew install macos-fuse-t/homebrew-cask/fuse-t
> brew install macos-fuse-t/homebrew-cask/fuse-t-sshfs
