### ISSUE TITLE
sshfs user@localhost works?

### ISSUE THREAD

**Issue by pahome** [libfuse/sshfs#31]
can i mount local disk /dev/sda by sshfs?
eg sshfs user@localhost:/dev/sda /mnt

**Comment by Nikratio** [comment]
No, this does not work.

**Comment by pahome** [comment]
is that ok to do sshfs like this ?
eg. sudo sshfs -o allow_other user@localhost:~/test /mnt
cuz i tried today but i can't have permission to create file in /mnt even change to root
