### ISSUE TITLE
Strange data corruption with sshfs+samba

### ISSUE THREAD

**Issue by matiaspl** [libfuse/sshfs#33]
I have a peculiar case with one fuse sshfs mount shared over samba with a couple of windows workstations. I have narrowed down the case to interoperability - it's not network, it's not SMB protocols used, it's not ssh nor samba versions on the machine sharing the files over samba. The data doesn't get corrupted when using sshfs/sftp alone.
So the case is: every 4k-th byte in the target file gets zeroed. Does anyone have a clue what could be happening?

**Comment by Nikratio** [comment]
Doesn't seem like anyone has an idea, so I'm closing the issue for now. There doesn't seem to be much we can do at the moment.

**Comment by matiaspl** [comment]
The issue was resolved by upgrading the ssh on the remote server machine. Very strange. As the problem does not show on recent linux distros it's reasonable to close this one. Thanks anyway :)
