### ISSUE TITLE
regression 2.7 -> 2.8 causing system hang.

### ISSUE THREAD

**Issue by james-lawrence** [libfuse/sshfs#35]
The last few months I've been experiencing hangs on my system when using sshfs, I upgraded from 2.7 to 2.8 in early-mid august.

Today I reverted back to 2.7 and was completely hang free. I've going to leave sshfs at 2.7 for a few more days and see if I experience anymore hangs but this weekend I'll be putting 2.8 and seeing if it hangs again. But atm it looks like 2.8 caused a serious regression.

**Comment by james-lawrence** [comment]
ran for a week without issues on 2.7, today I updated back to 2.8 and experience the system freeze again.

**Comment by Nikratio** [comment]
Could you start sshfs in debug mode (`-d -f -s`) and post the last output before it hangs? If possible, please also attach a debugger (`gdb -p <pid>`) and post the backtrace (`bt`).

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Comment by james-lawrence** [comment]
np, I stopped using sshfs because of it, and didn't have the time to reproduce. sorry.
