### ISSUE TITLE
command-line options to ssh not superseding .ssh/config settings

### ISSUE THREAD

**Issue by bjmuld** [libfuse/sshfs#36]
Have ~/.ssh/config setup to multiplex connections to all hosts.  I don't want sshfs to multiplex its connection, however, so I'm invoking:
                  sshfs host /mount/point -o ControlMaster=yes,ControlPath=none
expecting that no control sockets will be created.  I've checked and using:
                  ssh -o ControlMaster=yes,ControlPath=none host
Correctly overrides the settings in ~/.ssh/config.

It seems that sshfs is not applying the command-line options in such a way that that properly override the ~/.ssh/config settings.  

I have also tried creating a separate ~/.ssh/special.config file and used:
                    sshfs -F ~/.ssh/special.config
In this case as well, the options used are the ones set in  ~/.ssh/config rather than the ones set in ~/.ssh/special.config

what's going on???

----------------------------
SSHFS version 2.5
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19

**Comment by bjmuld** [comment]
want to add that sshfs is not recognizing the -o ControlPersist=no option either

**Comment by Nikratio** [comment]
Could you please run with `-f -o sshfs_debug`? This should tell you the exact way that ssh is called. For example:

```
$ sshfs -f -o sshfs_debug,ControlMaster=yes,ControlPath=none localhost:/tmp/ ~/tmp/mnt 
SSHFS version 2.5
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oControlMaster=yes> <-oControlPath=none> <-2> <localhost> <-s> <sftp>
Server version: 3
[...]
```

As far as I can tell, the options are passed on correctly.

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
