### ISSUE TITLE
Unable to mount any remote filesystem using sshfs

### ISSUE THREAD

**Issue by Shellcat-Zero** [libfuse/sshfs#39]
I upgraded libc6 on a stock Ubuntu 14.04 server to Xenial (16.04), which caused sshfs to stop being able to mount anything.  I reverted all packages back to trusty-updates, but the problem persists.  I appear to have replicated the bug reported at http://unix.stackexchange.com/questions/299730/unable-to-mount-any-remote-filesystem-using-sshfs.

The version of sshfs was 2.5.1.  I uninstalled and then installed the latest version from this Github repo, to no avail.
```
sshfs --version
SSHFS version 2.8
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19
```

Before mounting (as normal user):
```
ls -lh
drwxrwxr-x  2 user user 4.0K Dec 25 00:10 mnt/
```
Then attempting to mount:
```
sshfs thisuser@thisaddress.org:/media/drive /home/user/mnt
fusermount: failed to access mountpoint /home/user/mnt: Permission denied

ls -lh
ls: cannot access mnt: Transport endpoint is not connected
d?????????  ? ?          ?             ?            ? mnt/
```

The messed up directory can then only be remedied by issuing sudo fusermount -u mnt (root is requred to fix it).

If the drive is attempted by root, I get the message:
```
mount:  according to mtab, [site] is already mounted on [mountpoint]
```
It does not appear to be present in /etc/mtab, here is my /etc/mtab:
```
/dev/sda1 /boot/efi vfat rw,noatime,umask=0077 0 0
/dev/sda4 /home ext4 rw,noatime 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,noexec,nosuid,nodev 0 0
none /sys/fs/cgroup tmpfs rw,uid=0,gid=0,mode=0755,size=1024 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,noexec,nosuid,nodev,none,name=systemd 0 0
```

I have also noticed this bug triggered after attempting the sshfs mount:
```
df -lh
df: ‘/run/user/1000/gvfs’: Transport endpoint is not connected
...
```

Invoking sshfs with '-o sshfs_debug' simply prints the version number, and no further useful information.
On a system with a working sshfs, I can see fuse entries in the mtab, like a gvfsd-fuse entry listing the username, and successfully mounting the drive will show it in the mtab as well.  I've reinstalled sshfs and all of its dependencies several times.  I've been wrestling with this issue for days, assistance would be appreciated.

**Comment by Nikratio** [comment]
Are you still having this problem? If so, please post the output of:

```
cat /proc/mounts
ls -l <your-mountpoint>
sshfs <other-opts> <your-mountpoint>
```

**Comment by Shellcat-Zero** [comment]
@Nikratio I had no choice but to reinstall 16.04 from scratch to fix this issue.  I suspect some dependency, or version thereof, was not well accounted for, but otherwise I do not know the cause of the problem.

**Comment by Nikratio** [comment]
Alright, closing this bug then.
