### ISSUE TITLE
Path length limit?

### ISSUE THREAD

**Issue by threefcata** [libfuse/sshfs#42]
When the path to a file exceeds a limit, the path is truncated and results in a 'file not found' error on the remote host, failing to operate on the file. In my case, I tried to open a file and failed, turning on debug allowed me to discover this issue.

**Comment by Nikratio** [comment]
Thanks for the report! Could you provide an example (remote path name and local mounpoint) that reproduces this issue?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
