### ISSUE TITLE
does not support libfuse 3.x

### ISSUE THREAD

**Issue by thehesiod** [libfuse/sshfs#43]
first issue is that it's only checking for the "fuse" package

second issue is that it doesn't support the 3.x APIs
```c
In file included from /usr/local/include/fuse3/fuse.h:19:0,
                 from sshfs.c:12:
/usr/local/include/fuse3/fuse_common.h:724:4: error: #error only API version 30 or greater is supported
```

**Comment by kyrios123** [comment]
unfortunately the new release of sshfs (version 2.9) still does not support it... which is quite surprising since both sshfs and fuse are part of the same project !

**Comment by Nikratio** [comment]
Patches welcome!

**Comment by eli-schwartz** [comment]
Since 34146444ce20c477cba7e9fe113e4387da32ae94 moved to libfuse 3.x this can be closed now...
