### ISSUE TITLE
sshfs date bug (signed/unsigned)

### ISSUE THREAD

**Issue by 9omorra** [libfuse/sshfs#44]
Hi,

I found a little bug on sshfs 2.5 on Debian Jessie on amd64 (both server and
client). I copied files from one host to another via sshfs and the date
(mtime) of the copied file was 2106-02-07 instead of 1970-01-01.
If you look at the seconds since epoch, it is +0xffffffff instead of -1.
IMHO sshfs should try to preserve the date information even in edge cases
like this. I assume the bug still exists in the latest version of sshfs.

I have attached a simple shell script to reproduce the bug and a second file
with the output of this script.

Thanks,
9omorra

[sshfsbug.sh.txt](https://github.com/libfuse/sshfs/files/744784/sshfsbug.sh.txt)
[sshfsbug-log.txt](https://github.com/libfuse/sshfs/files/744809/sshfsbug-log.txt)

**Comment by Nikratio** [comment]
Thanks for the report! I'll take a look.

**Comment by Nikratio** [comment]
This works fine for me:

```
$ sh sshfsbug.sh.txt
creating test directory
mounting via sshfs on localhost:
local stat:
  File: ‘srcfile’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fe03h/65027d	Inode: 1440430     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/nikratio)   Gid: ( 1000/nikratio)
Access: 1970-01-01 00:59:59.000000000 -0500
Modify: 1970-01-01 00:59:59.000000000 -0500
Change: 2017-06-05 07:43:55.785809126 -0400
 Birth: -
1970-01-01 00:59:59.000000000 -0500;21599
remote stat of same file:
  File: ‘remote/srcfile’
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 2fh/47d	Inode: 2           Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/nikratio)   Gid: ( 1000/nikratio)
Access: 1970-01-01 00:59:59.000000000 -0500
Modify: 1970-01-01 00:59:59.000000000 -0500
Change: 1970-01-01 00:59:59.000000000 -0500
 Birth: -
1970-01-01 00:59:59.000000000 -0500;21599
unmount

$ cat /etc/debian_version 
8.8

$ sshfs --version
SSHFS version 2.5
FUSE library version: 2.9.3
fusermount version: 2.9.3
using FUSE kernel interface version 7.19
```

What's the output of these commands on your system?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Comment by thomasmerz** [comment]
Hey @Nikratio , some years ago I also found something that might be a bug - and reported it to a fork of your repo: https://github.com/deadbeefsociety/sshfs/issues/4 (don't know why I issued it there and not here? 🤔 )
So can you please have a look at it to see if it's worth to open an issue here? Many thanks!
