### ISSUE TITLE
force mounted filesystem to update contents

### ISSUE THREAD

**Issue by jeremybundgaard** [libfuse/sshfs#45]
I typically work on a remote cluster (linux) and sshfs mount a drive on my mac. I then ssh into the remote system and run commands that generate analysis plots that I view locally on my mac.  The time between when the file are created on the remote cluster and when they appear in finder for viewing can take any where from 10s of seconds to minutes.

I currently mount via 
-o Compression=no,follow_symlinks,auto_cache,reconnect,defer_permissions,noappledouble,volname=foo

Are there any terminal commands on either my client or server that force the sshfs mount to reload/refresh/update the remote filesystem content?

Please answer this question directly without offering other mount options.  I'm specifically wanting to find a command that I can run that "forces" the sshfs mount to update. Thanks!

**Comment by Nikratio** [comment]
There is no such command, sorry.

**Comment by Hello1024** [comment]
For anyone finding this later...

You can unmount and remount to clear any caches and see a fresh version of the remote system.   Automate it with a script and assign a hotkey and it becomes easy.   Downside:   Any open files will break.
