### ISSUE TITLE
Caching under OS X not working

### ISSUE THREAD

**Issue by qarl** [libfuse/sshfs#46]
When I open a file using standard OS X software (Quicktime Player, Preview, etc.) the files are not properly cached.  Opening a second time takes as long as the first time.

If I use a command line tool to read the file (cat file.mp4 > /dev/null) the file is correctly cached.  And if I then try to open the file with Quicktime Player, it opens instantly.

This might be explained (I am uncertain) if the standard OS X software uses some alternative to read() to access the files.  Perhaps mmap()?

Many thanks in advance.

**Comment by Nikratio** [comment]
Thanks! Could you check if this is an sshfs specific problem, or does it happen with every FUSE filesystem? Under Linux, FUSE comes with a "passthrough" example. Is there maybe something similar for OS-X?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
