### ISSUE TITLE
cannot connect when username contains colons

### ISSUE THREAD

**Issue by silvestre** [libfuse/sshfs#48]
I'm trying to connect to a system where the user names include colons. While ssh and sftp use the whole string before the @ as user name, sshfs stops at the first : and uses the preceding string as host name.

```
ssh cf:627ebba7-9d9e-4d28-af35-edb@ssh.cf.example.com
cf:627ebba7-9d9e-4d28-af35-edb@ssh.cf.example.com's password:
```

```
sshfs cf:627ebba7-9d9e-4d28-af35-edb@ssh.cf.example.com ~/tmp/sshfs -o sshfs_debug,port=2222,debug
SSHFS version 2.8
FUSE library version: 2.9.4
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oport=2222> <-2> <cf> <-s> <sftp>
```

**Comment by Nikratio** [comment]
Thanks for the report! I'll take a look,

**Comment by Nikratio** [comment]
I don't think there's a way to fix this. Consider e.g. `jeff:/home/@tags/work/`? With your interpretation, this would be parsed as the user "jeff:/home/" connecting to the host `@tags/work` - but it should be the default user connecting to the directory `@tags/work` on host `jeff`.

**Comment by Nikratio** [comment]
Closing this for now, feel free to re-open if I missed something. I think as a general rule, having usernames with colons in them is a bad idea.
