### ISSUE TITLE
mounted shares in /home/<user> appears twice

### ISSUE THREAD

**Issue by kyrios123** [libfuse/sshfs#50]
I have added the following entry in `/etc/fstab` to mount a share in my gome directory:
```
py@192.168.1.31:/home /home/py/py-nas fuse.sshfs noauto,x-systemd.automount,_netdev,noatime,user,nonempty,idmap=user,uid=1000,gid=1000,identityfile=/home/py/.ssh/id_rsa,allow_other,default_permissions,reconnect 0 0
```
It works fine but it appears twice as you can see here under. I think it only happen with `fuse.sshfs` filesystems

![image](https://cloud.githubusercontent.com/assets/7815316/24567296/5996181e-165d-11e7-94b3-618744fb7706.png)

**Comment by Nikratio** [comment]
This looks more like a problem in whatever file browser you are using. I don't think sshfs can do anything about that, sorry!

**Comment by kyrios123** [comment]
Thanks for the reply !
Still I am a little puzzled because I don't face such an issue if I mount the drive with NFS or Samba.
