### ISSUE TITLE
transform_symlinks ignored

### ISSUE THREAD

**Issue by HaleTom** [libfuse/sshfs#51]
With `transform_symlinks`:

```(ins)ravi@svelte:~/mnt$ sshfs -o transform_symlinks ravidroid: ravidroid
All keys already loaded
(ins)ravi@svelte:~/mnt$ ls -l ravidroid/ext
lrwxrwxrwx 1 root root 19 Apr  1 15:45 ravidroid/ext -> /storage/2EE0-1B07/
(ins)ravi@svelte:~/mnt$
```
However, `follow_symlinks` works:
```
(ins)ravi@svelte:~/mnt$ sshfs -o follow_symlinks ravidroid: ravidroid
(ins)ravi@svelte:~/mnt$ ls -ld ravidroid/ext
drwxrwx--x 1 root 1015 32,768 Mar 31 13:17 ravidroid/ext
(ins)ravi@svelte:~/mnt$ 
```

1. Should the manpage distinguish `transform_symlinks` from `follow_symlinks`?

1. Perhaps [the FAQ entry](https://github.com/libfuse/sshfs/blob/master/FAQ#L152) also needs an update.

**Comment by Nikratio** [comment]
I don't quite understand. The manpage already make a clear distinction:

```
       -o transform_symlinks
              transform absolute symlinks to relative

       -o follow_symlinks
              follow symlinks on the server
```

From what you've posted, I also don't see where *transform_symlinks* is being ignored.

Can you clarify?

**Comment by HaleTom** [comment]
I think I've finally wrapped my head around this.

I'd suggest the following update with example:
```
       -o transform_symlinks
               Transform absolute symlinks as if they were being accessed remotely. 
               If `d` is a symlink to `/`,  this option will have `ls d` list the contents of the remote root directory
```

You may want to add:
    This is done before 

------

For `follow_symlinks`, perhaps the explanation text could be more explicit:

       Dereference symbolic links. Accessing a symlink will access the file that is being referenced.
       Option `transform_symlinks` will affect how the dereferencing occurs.


    

dereferenct symlinks on the server on the server

**Comment by Nikratio** [comment]
Uhm, I don't see how `transform_symlinks` will have any effect when `follow_symlinks` is specified. Or are you talking about dangling symlinks here?

**Comment by HaleTom** [comment]
Brilliant, thanks for documenting this!

Sorry, I don't know enough to answer your question, but you've covered my concern.

**Comment by albertz** [comment]
@Nikratio 
Why is this closed? This is still broken. `transform_symlinks` does nothing. From the documentation, I was expecting that it transforms absolute symlinks to relative symlinks. Is that wrong? I still see all symlinks as absolute symlinks.
