### ISSUE TITLE
Unable to properly install sshfs with debug symbols

### ISSUE THREAD

**Issue by mrjextreme6** [libfuse/sshfs#56]
My sshfs is currently crashing when performing a remote mount on a redundant debian system.  I'm trying to install `sshfs-dbg` and `fuse-dbg` to get the debug symbols to hopefully provide useful information on why it's crashing.  I ran the apt install command for both packages and they run fine.  But when I run `file` on `sshfs` and `libfuse`, it still reports them as "stripped" (which is without debug symbols as I understand it). What am I missing?

FYI it's debian 7 with sshfs version 2.4.1

**Comment by Nikratio** [comment]
Debug debug symbols are shipped in separate files, so "file" will always tell you the binary is unstripped. When you run `gdb`, it should nevertheless be able to find the debug information.
