### ISSUE TITLE
sshfs: type of file differs from mountpoint

### ISSUE THREAD

**Issue by ashishkataria** [libfuse/sshfs#57]
Hi all, 

sshfs --version
SSHFS version 2.8
FUSE library version: 2.5.0
fusermount version: 2.5.0
using FUSE kernel interface version 7.5

I am trying to mount remote windows filesystem folder to linux server. I have installed openSSH on windows pc and  sshfs  on my linux server. 

         `          sshfs -o allow_other test@10.199.62.156:/cygdrive/d/test     /mnt/`

error comes as:
test@10.199.62.156:/cygdrive/d/test: **type of file differs from mountpoint**

How to resolve this?

**Comment by Nikratio** [comment]
That's probably because the host is using Windows, and sshfs expects Unix semantics. Not sure if that is easily fixable, but I'll take a look.

**Comment by ashishkataria** [comment]
I thought using sshfs we can mount remote windows filesystem folder to linux server and libfuse takes care of that.  Can it be fixed? Thanks Nikratio.

**Comment by Nikratio** [comment]
I don't know if this particular issue can be fixed. But in general I think you'd be better of using Samba and SMB/CIFS shares for this purpose.

**Comment by ashishkataria** [comment]
SMB/CIFS protocol is blocked due to security reasons after wannacry virus attack. Therefore as an alternative, I looked to SSHFS. I don't know any other option if it's there.

**Comment by Nikratio** [comment]
As an experiment, you could just comment out the check (line 1761-1765 in sshfs.c) and see if things work.

**Comment by ashishkataria** [comment]
After commenting those lines, while make install it geves few warnings as:

     sshfs.c: In function ‘sshfs_fsync’:
     sshfs.c:2643: warning: suggest parentheses around assignment used as truth value
     sshfs.c: In function ‘main’:
      sshfs.c:3946: warning: unused variable ‘libver’
     sshfs.c: At top level:
    sshfs.c:1172: warning: ‘connect_slave’ defined but not used
    sshfs.c:1179: warning: ‘connect_to’ defined but not used
   mv -f .deps/sshfs-sshfs.Tpo .deps/sshfs-sshfs.Po
   gcc -D_FILE_OFFSET_BITS=64 -D_REENTRANT -I/usr/local/include/fuse -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  -g -O2 -Wall -W   -o sshfs sshfs-sshfs.o sshfs-cache.o   -L/usr/local/lib -lfuse -lpthread -lgthread-2.0 -lpthread -lglib-2.0
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c sshfs '/usr/local/bin'
test -z "/usr/local/lib" || /bin/mkdir -p "/usr/local/lib"
/usr/bin/install -c -m 755 sshnodelay.so "/usr/local/lib/sshnodelay.so"
 /bin/mkdir -p '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 sshfs.1 '/usr/local/share/man/man1'
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/root/sshfs-2.8'
make: warning:  Clock skew detected.  Your build may be incomplete.
`

**Comment by ashishkataria** [comment]
Nikratio,
Now also it gives the same error:
       type of file differs from mountpoint

**Comment by Nikratio** [comment]
That's not possible. If you comment out the code that generates the error, then you cannot possibly continue to get it. Please re-check how you edited the file :-).

**Comment by ashishkataria** [comment]
Nikratio,

Sorry, VI editor has pointed to different code on those lines, and i commented out wrong part.
Now It worked man!   
Thanks 

Were these lines of code any useful?

**Comment by Nikratio** [comment]
Well, hard to say. It's effectively a consistency check. But if that's the only thing that prevents sshfs from working with a Windows client, then maybe we ought to remove it.
