### ISSUE TITLE
sshfs won't accept redirect of debugs to a file in background mode

### ISSUE THREAD

**Issue by boMac** [libfuse/sshfs#58]
Hi, Need to turn on sshfs debugs, but have them go to a file in background mode. Running below from withing a bash script. What happens is once debugs are turned on, sshfs grabs the console and does not release it, until user does ctrl-c. i.e. the redirect is not working. Please indicate how to do above.  Here I ran the command from the csh of the guest and you can see sshfs (fuse) consders 2 to be an invalid argument and does not go to background mode for recording the debugs. (BTW, the /tmp/sshfs.log does get written).

oot@:/etc/rc.d # setfib -F1 sshfs -o StrictHostKeyChecking=no,follow_symlinks,transform_symlinks,no_check_root,Compression=no,LogLevel=debug3,debug 10.0.0.4:/var/foo /var/foo -o intr 2>/tmp/sshfs.log&
[1] 8781
root@:/etc/rc.d # fuse: invalid argument `2'

[1]    Exit 1                        setfib -F1 sshfs -o StrictHostKeyChecking=no,follow_symlinks,transform_symlinks,no_check_root,Compression=no,LogLevel=debug3,debug 10.0.0.4:/var/foo /var/foo -o intr 2 > /tmp/sshfs.log

**Comment by Nikratio** [comment]
Look at the error message. You are not redirecting stderr to a file ('2> file'), but you are passing '2' as an argument to sshfs and then redirect stdout.
