### ISSUE TITLE
No copy progress indicator in Nautilus 

### ISSUE THREAD

**Issue by benjamindaines** [libfuse/sshfs#59]
If I'm copying something from an sshfs mount point to a local drive with Nautilus there is no progress indicator and I must watch network activity in System Monitor in order to hopefully see when the copy operation is finished.  

Arch Linux:
Nautilus 3.24.1
sshfs 2.9-1

**Comment by Nikratio** [comment]
What's that got to do with sshfs? If Nautilus doesn't show you a progress dialog, you'll need to bring that to the Nautilus developers :-).
