### ISSUE TITLE
sshfs is very slow compared to scp

### ISSUE THREAD

**Issue by shuokay** [libfuse/sshfs#63]
I am using Macbook, and mount a remote cenos machine.
1. when  `ls` in terminal, all files displayed immediately but the promote show up after several seconds.
2. When play a video about 100M, the play is not smooth, but when `scp` this video to local machine it takes less than 5 seconds.

**Comment by Jakuje** [comment]
And where is the comparison to the `scp`?

**Comment by shuokay** [comment]
@Jakuje updated the comment

**Comment by Nikratio** [comment]
Looks like a duplicate of #11 - please feel free to re-open if you have data that indicates that this has a different cause.
