### ISSUE TITLE
segfault with gcc7/fuse-3.1.0/sshfs-3.0.0

### ISSUE THREAD

**Issue by bdubbs** [libfuse/sshfs#68]
I don't know if this is a fuse or sshfs issue.  I built fuse-3.1.0 with:
#gcc version 7.1.0 (GCC)

./configure --prefix=/usr   --disable-static   --exec-prefix=/
make
make install

and built sshfs-3.0.0 with:

./configure --prefix=/usr 
make
make install

Running, I get:

$ sshfs higgs: test-sshfs
Segmentation fault

A simple 'ssh higgs' works fine.  Rebuilding sshfs-2.9/fuse-2.9.7 also works fine.

gdb says:
(gdb) bt
#0  0x00007ffff71464ec in _int_malloc (av=av@entry=0x7ffff746ab00 <main_arena>, 
    bytes=bytes@entry=49) at malloc.c:3349
#1  0x00007ffff71477e8 in _int_realloc (av=av@entry=0x7ffff746ab00 <main_arena>, 
    oldp=oldp@entry=0x613f10, oldsize=oldsize@entry=48, nb=nb@entry=64) at malloc.c:4311
#2  0x00007ffff71485fe in __GI___libc_realloc (oldmem=0x613f20, bytes=41)
    at malloc.c:3045
#3  0x00007ffff7bb79f9 in add_opt_common (opts=0x7fffff7ff210, 
    opt=0x619890 "fsname=higgs:", esc=1) at fuse_opt.c:117
#4  0x00007ffff7bb802b in process_gopt (ctx=ctx@entry=0x7fffff7ff1d0, 
    arg=arg@entry=0x619890 "fsname=higgs:", iso=iso@entry=1) at fuse_opt.c:290
#5  0x00007ffff7bb80ff in process_real_option_group (opts=<optimized out>, 
    ctx=<optimized out>) at fuse_opt.c:306
#6  process_option_group (ctx=0x7fffff7ff1d0, opts=<optimized out>) at fuse_opt.c:342
#7  0x00007ffff7bb83e6 in process_one (arg=<optimized out>, ctx=0x7fffff7ff1d0)
    at fuse_opt.c:358
#8  opt_parse (ctx=0x7fffff7ff1d0) at fuse_opt.c:378
#9  fuse_opt_parse (args=args@entry=0x7fffffffdc80, data=data@entry=0x7fffff7ff290, 
    opts=opts@entry=0x7fffff7ff240, proc=proc@entry=0x7ffff7ba8780 <fuse_lib_opt_proc>)
    at fuse_opt.c:413
...

I also note that the man page for sshfs-3.0.0 still says "SSHFS version 2.0   April 2008" in the footer.

**Comment by bdubbs** [comment]
Commit 503e32d0 for libfuse seems to have fixed the problem.  There probably should be a fuse-3.1.1 release.

**Comment by Nikratio** [comment]
Closing per most recent comment.

Any reason you're not building with Meson? As the README says, autoconf support may go away at some point. So if you depend on it, make yourself heard.

**Comment by bdubbs** [comment]
Linux From Scratch does not have Meson yet.  When packages require it, we will be forced to add it.
