### ISSUE TITLE
support mount with ssh private key 

### ISSUE THREAD

**Issue by sequoiar** [libfuse/sshfs#71]
can sshfs support ssh private key instead of password ?

**Comment by Jakuje** [comment]
It already does, if you configure underlying `ssh` to use the private SSH key. There is no way for SSH to use SSL key (whatever you mean by that).

**Comment by sequoiar** [comment]
@Jakuje like sshfs -i private.key   user@remote-host:/dir  .

**Comment by Jakuje** [comment]
No, there is no such argument for `sshfs`. But you can use `-o IdentityFile=private.key` or put the following into the `~/.ssh/config`, which will get used by the `ssh:

    IdentityFile=private.key
