### ISSUE TITLE
Tilde in host path gives odd results

### ISSUE THREAD

**Issue by heirecka** [libfuse/sshfs#74]
If I try to mount a remote filesystem (sshfs host /foo/mntpoint) I only get some kind of help screen:

>   -o kernel_cache        cache files in kernel
    -o [no]auto_cache      enable caching based on modification times (off)
    -o umask=M             set file permissions (octal)
    -o uid=N               set file owner
    -o gid=N               set file group
    -o entry_timeout=T     cache timeout for names (1.0s)
    -o negative_timeout=T  cache timeout for deleted names (0.0s)
    -o attr_timeout=T      cache timeout for attributes (1.0s)
    -o ac_attr_timeout=T   auto cache timeout for attributes (attr_timeout)
    -o noforget            never forget cached inodes
    -o remember=T          remember cached inodes for T seconds (0s)
    -o modules=M1[:M2...]  names of modules to push onto filesystem stack
    -o allow_other         allow access by all users
    -o allow_root          allow access by root
    -o auto_unmount        auto unmount on process termination
>
> Options for subdir module:
    -o subdir=DIR           prepend this directory to all paths (mandatory)
    -o [no]rellinks         transform absolute symlinks to relative
>
> Options for iconv module:
    -o from_code=CHARSET   original encoding of file names (default: UTF-8)
    -o to_code=CHARSET      new encoding of the file names (default: UTF-8)`

The same command worked with 2.9.0 and I don't see any error indicating what I'm doing wrong.

**Comment by Nikratio** [comment]
What's the exact command that you are calling?

**Comment by heirecka** [comment]
Just "sshfs host: /mountpoint" where mountpoint exists and is read- and writable by my user.

**Comment by Nikratio** [comment]
Works for me. Can you please *copy & paste* the *exact* commands that you use, and the output that you get? For me it looks like this:

```
$ ./sshfs host: /mountpoint
sshfs: bad mount point `/mountpoint': No such file or directory

[1] nikratio@vostro:~/in-progress/sshfs/build
$ ./sshfs host: ~/tmp/mnt
read: Connection reset by peer
```

**Comment by heirecka** [comment]
```
$ sshfs --version
SSHFS version 3.0.0
FUSE library version 3.1.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.0

$ sshfs host: /non-existant-dir
sshfs: bad mount point `/non-existant-dir': No such file or directory

$ sshfs host:~ /mnt/host
    -o kernel_cache        cache files in kernel
    -o [no]auto_cache      enable caching based on modification times (off)
    -o umask=M             set file permissions (octal)
    -o uid=N               set file owner
    -o gid=N               set file group
    -o entry_timeout=T     cache timeout for names (1.0s)
    -o negative_timeout=T  cache timeout for deleted names (0.0s)
    -o attr_timeout=T      cache timeout for attributes (1.0s)
    -o ac_attr_timeout=T   auto cache timeout for attributes (attr_timeout)
    -o noforget            never forget cached inodes
    -o remember=T          remember cached inodes for T seconds (0s)
    -o modules=M1[:M2...]  names of modules to push onto filesystem stack
    -o allow_other         allow access by all users
    -o allow_root          allow access by root
    -o auto_unmount        auto unmount on process termination
 
Options for subdir module:
    -o subdir=DIR           prepend this directory to all paths (mandatory)
    -o [no]rellinks         transform absolute symlinks to relative

Options for iconv module:
    -o from_code=CHARSET   original encoding of file names (default: UTF-8)
    -o to_code=CHARSET      new encoding of the file names (default: UTF-8)
```

The latter output is the same, regardless if <host> exists and is reachable via ssh.

**Comment by Nikratio** [comment]
Aha! You did not mention the tilde (`~`) before. That is not a valid path, even if your shell may trick you into thinking that by allowing its use in some situations.

That said, I admit that SSHFS response to this is..sub-optimal.

**Comment by Nikratio** [comment]
Duh, I still can't reproduce your specific problem though. I am getting the expected output even with tilde:

```
$ ./sshfs localhost:~ ~/tmp/mnt
localhost:~: No such file or directory
```

Is this on Linux or OS X?

**Comment by heirecka** [comment]
Doesn't matter if I add a tilde or not, or add an explicit remote dir. Also, I'm pretty sure the tilde worked with 2.9.0.

I'm on Linux.

**Comment by Nikratio** [comment]
How very odd. Which shell are you using when entering the command? Can you try with bash if you're using something else?

The only thing that comes to mind is that maybe something is expanding the tilde before sshfs sees it.

**Comment by heirecka** [comment]
Although, I don't understand completely it's fixed for me now.

After using gcc-6.4.0 (instead of 7.1.0) to build I got a crash and a backtrace pointing to libfuse and involving some versioned symbols, which lead me to 503e32d, 5a5edc3 and 100944b. With these three commits added on top of the libfuse-3.1.0 tarball, everything works fine now.

So I guess this issue can be closed now.

**Comment by Nikratio** [comment]
Alright, thanks for checking!

**Comment by albertvaka** [comment]
@heirecka I'm having the exact same problem, but I'm not building anything from scratch... can you clarify a bit the solution? Did you have to manually patch libfuse to make it work? Is it a bug on fuse then? It shouldn't be necessary to patch anything for a stable version of sshfs to work, and this happens right now on the latest released version as distributed by Arch Linux.

**Comment by heirecka** [comment]
Git reminds me that I applied three patches to libfuse-3.1.0: https://git.exherbo.org/arbor.git/commit/packages/sys-fs/fuse?id=58b3eabe4e31b14cc6a12eba2c610cfdc984a64c (the udev pkgconfig patch is not relevant for the problem at hand), but those are all contained in libfuse-3.1.1. So either apply them to an earlier version or update.

**Comment by albertvaka** [comment]
Already on 3.1.1, same issue:
```
vaka@Thor:~$
SSHFS version 3.2.0
FUSE library version 3.1.1
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.1
```

**Comment by heirecka** [comment]
Sorry, no spontaneous idea then. Still works here with the same versions you have.
