### ISSUE TITLE
fuse: unknown option(s): `-o cache=no'

### ISSUE THREAD

**Issue by Soukyuu** [libfuse/sshfs#78]
Hello,

I've recently updated my arch linux installation and all of my sshfs shares stopped mounting. Attempting to mount manually via
```
# mount -a
```
gives me a `fuse: unknown option(s): '-o cache=no'` for every of my sshfs shares. `man sshfs` still lists the option, however.

I'm running the following at the moment:
```
SSHFS version 3.0.0
FUSE library version 3.1.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.0
```
A sample non-working `/etc/fstab` entry:
```
myuser@192.168.1.2:/mnt/data/share             /home/myuser/Share       fuse.sshfs      x-systemd.automount,idmap=user,port=12345,_netdev,identityfile=/home/myuser/.ssh/id_rsa,allow_other,default_permissions,uid=1000,gid=1005,reconnect,cache=no,kernel_cache,compression=no 0 0
```
Removing `cache=no` from the entry solves the problem.

**Comment by Nikratio** [comment]
Thanks for the report! From the ChangeLog.rst file:

```
Release 3.1.0 (2017-08-04)
--------------------------

[...]
* For improved backwards compatibility, SSHFS now also silently
  accepts the old ``-o cache_*`` options.

Release 3.0.0 (2017-07-08)
--------------------------

[...]
* The `cache` option has been renamed to `dir_cache` for clarity.  
```

**Comment by Soukyuu** [comment]
Thanks for the fast reply! 
I guess the man page entry really wasn't changed accordingly then.
