### ISSUE TITLE
Unable to truncate files when writeback cache is active

### ISSUE THREAD

**Issue by DLaicH** [libfuse/sshfs#81]
Ever since upgrading sshfs to 3.x, I get permissions issues when saving files (from Atom text editor under Arch Linux, although I have issues in other editors too) that I didn't used to get under 2.x. When it first happened with 3.0.0, I downgraded back to 2 temporarily. I just installed 3.2.0, but I'm still having the issues.

After some experimentation, it seems to happen on files that I am not the owner of, but that I have permission to write via the group on the server. Granted, I have not set up any sort of gidfile, but it didn't seem to matter in 2.x, so I'm wondering what changed.

I can get it to work by setting writeback_cache=no, but once again, that didn't used to be necessary. Here is debugging info when writeback_cache=no:

```
[00314] OPEN
[00315] LSTAT
  [00314]         HANDLE       17bytes (1ms)
  [00315]          ATTRS       41bytes (1ms)
[00316] WRITE
[00317] WRITE
  [00316]         STATUS       28bytes (4ms)
  [00317]         STATUS       28bytes (4ms)
[00318] CLOSE
```

And here is debugging info without that option:
```
[00127] OPEN
[00128] LSTAT
  [00127]         HANDLE       17bytes (1ms)
  [00128]          ATTRS       41bytes (1ms)
[00129] WRITE
[00130] WRITE
[00131] FSETSTAT
  [00129]         STATUS       28bytes (4ms)
  [00130]         STATUS       28bytes (4ms)
  [00131]         STATUS       38bytes (6ms)
[00132] CLOSE
```

I assume it has something to do with that FSETSTAT, but I don't pretend to know how this stuff works exactly. :)

**Comment by Nikratio** [comment]
Thanks for the report! For one of the affected files, could you please check if you are able to truncate it (`truncate -s <size> <filename`). Please try to both increase and decrease the current file size (this will be destructive for the file, so make a backup of the file first).

**Comment by Nikratio** [comment]
(I mean truncate via the sshfs mount)

**Comment by DLaicH** [comment]
Thanks for the quick response!

`truncate: failed to truncate 'test2.txt' at 2 bytes: Permission denied`

```
[00040] LSTAT
  [00040]          ATTRS       41bytes (1ms)
[00041] LSTAT
  [00041]          ATTRS       41bytes (1ms)
[00042] OPEN
[00043] LSTAT
  [00042]         HANDLE       17bytes (0ms)
  [00043]          ATTRS       41bytes (0ms)
[00044] FSETSTAT
  [00044]         STATUS       28bytes (0ms)
[00045] FSETSTAT
  [00045]         STATUS       38bytes (0ms)
[00046] CLOSE
  [00046]         STATUS       28bytes (0ms)
```

**Comment by Nikratio** [comment]
Uhm. That's odd. I would not have expected the writecache setting to have any effect on truncate. Now I'm confused.

**Comment by Nikratio** [comment]
To debug this, we need to add some extra code that prints out the details of the FSETSTAT request so that I can see how it differs in the two cases.

**Comment by DLaicH** [comment]
Let me know what I can do to help debug this.

**Comment by Nikratio** [comment]
One approach would be to temporary modify the `sftp_request` method to print details about `buf` when `type` is `SSH_FXP_SETSTAT` or `SSH_FXP_FSETSTAT`. Far you'd need to re-parse `buf`. Alternatively, you could search for all places where `sftp_request` is called with SSH_FXP_SETSTAT` or `SSH_FXP_FSETSTAT` and emit debug messages as the `buf` argument is constructed.

**Comment by DaveMDS** [comment]
Exactly same problem here: cannot write to remote files that I do not own (but remote group permit write).

In my case (using the geany editor) when saving a file it is truncated on the remote and then I got the permission danied. The remote file is truncated at 0 bytes but not written.

As per @DLaicH suggestion adding the **writeback_cache=no** option to the sshfs command fix the issue
