### ISSUE TITLE
sshfs mount hang with ServerAliveInterval=1,ServerAliveCountMax=1 and bad password

### ISSUE THREAD

**Issue by jtmoon79** [libfuse/sshfs#87]
Mounting a remote directory with `sshfs` options `ServerAliveInterval=1,ServerAliveCountMax=1` and entering the wrong password causes `sshfs` to hang.

#### Undesired failure behavior

1. Set an empty config file to ensure consistent ssh options

       $ touch /tmp/empty

1. Run sshfs with the options

       $ sshfs user@ssh:/tmp /tmp/ssh -F /tmp/empty \
               -o NumberOfPasswordPrompts=1,ServerAliveInterval=1,ServerAliveCountMax=1

1. Enter the wrong password for `user@ssh` .
***BUG*** sshfs hangs.
This is undesirable behavior.  I would expect `sshfs` to recognize the bad password and then exit.
The process can be killed with `<ctrl+c>` keyboard input.
Additionally, the unsuccessful mount point remains mounted but is empty.

#### Desired failure behavior

Change either of the passed `-o` options `ServerAliveCountMax=1` or `ServerAliveInterval=1` . `sshfs` will not hang (desired behavior). For example, repeat the prior reproduction steps but remove
`ServerAliveCountMax=1`.

      $ sshfs user@ssh:/tmp /tmp/ssh -F /tmp/empty \
              -o NumberOfPasswordPrompts=1,ServerAliveInterval=1

Now `sshfs` fails after 4 seconds with error message

      read: Connection reset by peer

This is desirable failure behavior.

### Software used

    $ sshfs --version
    SSHFS version 2.5
    FUSE library version: 2.9.4
    fusermount version: 2.9.4
    using FUSE kernel interface version 7.19

On _Ubuntu 16.04.3_ using kernel _4.4.0-92_.

Originally reported as [Debian bug #873891](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=873891).

**Comment by Nikratio** [comment]
Thanks for the report, I'll look into it as soon as I can.

**Comment by Nikratio** [comment]
Sorry, are you saying that when you explicitly specify `-o NumberOfPasswordPrompts=1,ServerAliveInterval=1,ServerAliveCountMax=1` you want SSHFS to automatically drop either the `ServerAliveInterval` or `ServerAliveCountMax` option? This does not sound right to me.

**Comment by Nikratio** [comment]
Also, for me this works just fine:

```
$ touch /tmp/empty
$ md /tmp/ssh
$ sshfs user@localhost:/tmp /tmp/ssh -F /tmp/empty -o NumberOfPasswordPrompts=1,ServerAliveInterval=1,ServerAliveCountMax=1
user@localhost's password: 
read: Connection reset by peer
$ ./sshfs --version
SSHFS version 3.2.0
FUSE library version 3.1.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.0
```

**Comment by jtmoon79** [comment]
> when you explicitly specify `-o NumberOfPasswordPrompts=1,ServerAliveInterval=1,ServerAliveCountMax=1` you want SSHFS to automatically drop either the `ServerAliveInterval` or `ServerAliveCountMax` option? 

It seems like they should work fine together.  From `man ssh_config`,

     ServerAliveCountMax
             Sets the number of server alive messages (see below) which may be sent without ssh(1)
             receiving any messages back from the server.
             ...
             The default value is 3.  If, for example, ServerAliveInterval (see below) is set to 15 and
             ServerAliveCountMax is left at the default, if the server becomes unresponsive, ssh will
             disconnect after approximately 45 seconds.

     ServerAliveInterval
             Sets a timeout interval in seconds after which if no data has been received from the server,
             ssh(1) will send a message through the encrypted channel to request a response from
             the server.

AFAICT, setting `ServerAliveInterval=1,ServerAliveCountMax=1` will disconnect `ssh` if no data (or an "alive" message) has been received by the client from the server within 1 second.  Perhaps there is a race condition here.
