### ISSUE TITLE
if first invocation is cancelled before unlocking key, second invocation fails, requires unmount

### ISSUE THREAD

**Issue by dradetsky** [libfuse/sshfs#9]
Suppose I run `sshfs` having not yet `ssh-add`ed my key. I am then prompted to enter the password for my key. I want to enter my password only once, so I C-c the `sshfs` process, run `ssh-add`, then re-run `sshfs`. I assume that because I haven't given `sshfs` my unlocked key, nothing has happened, so the result will be that the second `sshfs` invocation mounts the filesystem.

The actual result is that the filesystem is somehow half-mounted. I don't yet fully understand what has happened, but the upshot is that it will not mount until I run `fusermount -uz $MOUNTPOINT` (The -z may not be required). 

I don't see any reason why beginning the mount before acquiring the key or password or whatever is desirable.

**Comment by dradetsky** [comment]
In case this has already been fixed upstream:

```
% sshfs -V
SSHFS version 2.5
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
```

**Comment by Nikratio** [comment]
Fully agree, patches are welcome :-).
