### ISSUE TITLE
idmap=file has no affect

### ISSUE THREAD

**Issue by jtmoon79** [libfuse/sshfs#90]
### On the server side

As user `root`

    $ mkdir /tmp/foo

#### create uidfile and gidfile

As user `root`, create uidfile and gidfile mappings

     $ echo "0:root
     1000:user1000" > /tmp/uidfile
     $ echo "0:root
     1000:user1000" > /tmp/gidfile
     $ chmod u=r,g=,o= -- /tmp/uidfile /tmp/gidfile

#### mount

     $ mkdir /tmp/foo
     $ sshfs root@server:/tmp/foo /tmp/foo -F /dev/null \
        -o allow_other \
        -o idmap=file,uidfile=/tmp/uidfile,gidfile=/tmp/gidfile \
        -o sshfs_sync \
        -o sync_readdir \
        -o no_readahead \
        -o cache=no

#### test

As user `user1000`,

    $ touch /tmp/foo/test-user1000
    $ ls -l /tmp/foo
        ...
        -rw-r--r-- 1 root root    0 Sep  5 12:43 test-user1000

**DEFECT**: the file is created with `root` permissions despite the mapping files.
**WORKAROUND**: `chown` of the files created to the desired user.

<br/>

----

Using client software versions

    $ sshfs --version
    SSHFS version 2.5
    FUSE library version: 2.9.4
    fusermount version: 2.9.4
    using FUSE kernel interface version 7.19

server software versions

    $ sshd -v
    OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016

**Comment by Nikratio** [comment]
Thanks for the report! I'll look into it as soon as I can.

**Comment by Nikratio** [comment]
According to the manpage, your mapfile has the wrong format:

```
-o uidfile=FILE
   file containing ``username:uid`` mappings for `-o idmap=file`

-o gidfile=FILE
   file containing ``groupname:gid`` mappings for `-o idmap=file`
```

Could you check if that helps?

**Comment by jtmoon79** [comment]
> your mapfile has the wrong format:
> ...
> Could you check if that helps?

Still fails.

I attempted again with corrected changes to the mapping files

     $ echo "root:0
     user1000:1000" > /tmp/uidfile
     $ echo "root:0
     user1000:1000" > /tmp/gidfile
     $ chmod u=r,g=,o= -- /tmp/uidfile /tmp/gidfile

And added parameters `nomap=ignore`

    $ sshfs root@server:/tmp/foo /tmp/foo -F /dev/null \
        -o allow_other \
        -o idmap=file,uidfile=/tmp/uidfile,gidfile=/tmp/gidfile,nomap=ignore \
        -o sshfs_sync \
        -o sync_readdir \
        -o no_readahead \
        -o cache=no

As user `root` on the client,

     $ touch /tmp/foo/test-root
     $ sudo -u user1000 -- touch /tmp/foo/test-user1000

Both newly `touch`ed files, `/tmp/foo/test-root` and `/tmp/foo/test-user1000`, were owned by user `root` and group `root`.

**Comment by Nikratio** [comment]
Currently, SSHFS applies the map file only when retrieving ownership information from the server, and (in reverse) when `chown` is explicitly called. The reason for that is that file creation happens on the server, and there is no way for SSHFS to specify that it should be done under a different UID - in general, this won't even be possible. When you log into a system via SSH as anything but root, any file that you create will be owned by your remote id. SSHFS is subject to the same limitations.

The only way to achieve the behavior you seem to want is to require the remote user being root, and to send an explicit `chown` request. I don't think this is a good idea.

**Comment by jtmoon79** [comment]
> The only way to achieve the behavior you seem to want is to require the remote user being root, and to send an explicit `chown` request.

This underlying behavior would fulfill my current use-case.  Obviously, up to you.  Appreciate the reply.

**Comment by Nikratio** [comment]
Hm. Ok. I don't really have a use for this, and apparently no one else so far has missed it either. So unless you are interested in preparing a patch that implements this, I'll close this issue. (I prefer to use the issue tracker as a tool to manage ongoing work rather than a database of possible enhancements and/or known issues)
