### ISSUE TITLE
Getting weird operation not permitted stuff

### ISSUE THREAD

**Issue by mingl0280** [libfuse/sshfs#91]
I'm using sshfs to access one of my NTFS file systems, and during the mounting / unmounting, i've got this weird errors that prevents me from writing a new file:
Both privileged user and non-privileged user are receiving this (root and non root)
```
root@vps32038:/mnt# sshfs -o allow_other,big_writes,no_check_root,IdentityFile=/root/id_rsa -o uid=$(id -u debian-transmission),gid=$(id -g debian-transmission),umask=0,sync_read,atomic_o_trunc,idmap=user,cache=no -f -d user@target.com:download /mnt/sshfs

FUSE library version: 2.9.4
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003fffb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000038
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 99, pid: 4780
LOOKUP /folder
getattr /folder
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: LOOKUP (1), nodeid: 2, insize: 44, pid: 4780
LOOKUP /folder/abc
getattr /folder/abc
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 4, opcode: CREATE (35), nodeid: 2, insize: 60, pid: 4780
create flags: 0x8241 /folder/abc 0100644 umask=0022
   unique: 4, error: -1 (Operation not permitted), outsize: 16
```
I've tried to use different combinations of options (including no umask; umask=2;no uid/gid;use (or not using) cache; async read and none of them works. it kept sending me the the Operation not permitted.), and ends in failure. Based on my server logs it looks like the server side sftp didn't even received the create command. 
Is there any idea on how to prevent this from happening?

**Comment by Nikratio** [comment]
Does the following information help? (from the manpage):

```
CAVEATS / WORKAROUNDS
   O_APPEND
       When  writeback  caching is enabled, SSHFS cannot reliably support the O_APPEND open
       flag and thus signals an error on open.  To enable support for  unreliable  O_APPEND
       (which  may  overwrite  data if the file changes on the server at a bad time), mount
       the file system with -o unreliable_append.
```

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
