### ISSUE TITLE
File attributes are not updated when writeback caching is active

### ISSUE THREAD

**Issue by ewirch** [libfuse/sshfs#93]
Using sshfs 3.2.0 / fuse 3.1.1

How to reproduce: mount using `dir_cache=no`:
```
sshfs me@remote:/home/me/somedir ./somedir -o dir_cache=no
```
List file contents of the folder so you see the modification date. Touch a file on remote. List the files locally again. The change date of the file will be the old one. Even 30mins later, the change date (and contents) of the file are not re-fetched.

**Comment by Nikratio** [comment]
Thanks for the report! IIRC the directory cache is for the *names* of the directory entries, not the attributes. Could you try to remove (or create) a file, and see if that update propagates as expected?

**Comment by ewirch** [comment]
New files are reported immediately.
However, I did not find a setting to disable caching of attributes/contents.

**Comment by Nikratio** [comment]
Take a look at `--help`:

```
    -o attr_timeout=T      cache timeout for attributes (1.0s)
    -o ac_attr_timeout=T   auto cache timeout for attributes (attr_timeout)
```

**Comment by ewirch** [comment]
I did look at this options. But as I said, attributes were not updated even after 30mins, which is much more than the default value of 1s for attr_timeout.

What's the default value for ac_attr_timeout?

**Comment by ewirch** [comment]
I did try `-o dir_cache=no -o attr_timeout=1.0 -o ac_attr_timeout=1.0` and also `-o dir_cache=no -o attr_timeout=0 -o ac_attr_timeout=0`. Both showed no effect. The attributes (and also the **contents!**) are never reloaded. I checked a folder this morning which I mounted yesterday. It still showed the old change dates for the files.

**Comment by Nikratio** [comment]
Alright, thanks for checking. I'll look into it as soon as I can.

**Comment by Nikratio** [comment]
Could you provide some more detailed instructions on how to reproduce this issue (ideally commands I can copy and paste)? On my system, I see a clear effect of turning dir_cache on/off:

```
$ cat ../issue_93.sh 
#!/bin/sh

mkdir /tmp/issue_93
touch /tmp/issue_93/file_1
mkdir /tmp/issue_93_mnt

echo "dir_cache=yes"
./sshfs -o dir_cache=yes localhost:/tmp/issue_93/ /tmp/issue_93_mnt/
echo "First ls:"
ls /tmp/issue_93_mnt/
touch /tmp/issue_93/file_2
echo "Second ls"
ls /tmp/issue_93_mnt/
fusermount -u /tmp/issue_93_mnt/

echo "dir_cache=no"
./sshfs -o dir_cache=no localhost:/tmp/issue_93/ /tmp/issue_93_mnt/
echo "First ls:"
ls /tmp/issue_93_mnt/
touch /tmp/issue_93/file_3
echo "Second ls"
ls /tmp/issue_93_mnt/
fusermount -u /tmp/issue_93_mnt/

rm -r /tmp/issue_93 /tmp/issue_93_mnt

$ ../issue_93.sh 
dir_cache=yes
First ls:
file_1
Second ls
file_1
dir_cache=no
First ls:
file_1	file_2
Second ls
file_1	file_2	file_3
```

In other words, with `dir_cache=yes` the new file is does not become visible in the mountpoint right away. With `dir_cache=no`, the file becomes visible right away.

**Comment by Nikratio** [comment]
I can reproduce some problems with caching of attributes. However, these seem to be caused by the server. Notice how SSHFS sends a new LSTAT request for the second stat call, but the SSH server still answers with the old data:

```
$ cat ../issue_93b.sh 
#!/bin/sh

mkdir /tmp/issue_93
touch /tmp/issue_93/file_1
mkdir /tmp/issue_93_mnt

echo "** attr_timeout=20 **"
./sshfs -d -f -o attr_timeout=1,dir_cache=no localhost:/tmp/issue_93/ /tmp/issue_93_mnt/ &
sleep 1
stat --format='%-30n: %y' /tmp/issue_93/file_1 /tmp/issue_93_mnt/file_1
sleep 60
touch /tmp/issue_93/file_1
stat --format='%-30n: %y' /tmp/issue_93/file_1 /tmp/issue_93_mnt/file_1
fusermount -u /tmp/issue_93_mnt/

$ ../issue_93b.sh 
[...]
/tmp/issue_93/file_1          : 2017-09-19 22:11:18.163312800 +0100
[00003] LSTAT
  [00003]          ATTRS       41bytes (0ms)
/tmp/issue_93_mnt/file_1      : 2017-09-19 22:11:18.000000000 +0100
/tmp/issue_93/file_1          : 2017-09-19 22:12:19.170903282 +0100
[00004] LSTAT
  [00004]          ATTRS       41bytes (0ms)
/tmp/issue_93_mnt/file_1      : 2017-09-19 22:11:18.000000000 +0100
```

It seems the SSH server is doing the caching on its side - but to be 100% sure we'd have to change SSHFS to print out the attributes that it reports from the second LSTAT call.

**Comment by Nikratio** [comment]
Note that if we make the sleep time shorter than the attribute and name caches, no LSTAT request is sent to the server (again, as expected):

```
$ cat ../issue_93c.sh 
#!/bin/sh

mkdir /tmp/issue_93
touch /tmp/issue_93/file_1
mkdir /tmp/issue_93_mnt

./sshfs -d -f -o attr_timeout=20,entry_timeout=20,dir_cache=no \
        localhost:/tmp/issue_93/ /tmp/issue_93_mnt/ &
sleep 1
stat --format='SSHFS: %y' /tmp/issue_93_mnt/file_1
stat --format='Local: %y' /tmp/issue_93/file_1
sleep 1
echo "Touching file.."
touch /tmp/issue_93/file_1
stat --format='SSHFS: %y' /tmp/issue_93_mnt/file_1
stat --format='Local: %y' /tmp/issue_93/file_1
fusermount -u /tmp/issue_93_mnt/

rm -r /tmp/issue_93 /tmp/issue_93_mnt
$ ../issue_93b.sh 
[...]
[00003] LSTAT
  [00003]          ATTRS       41bytes (0ms)
SSHFS: 2017-09-19 22:18:10.000000000 +0100
Local: 2017-09-19 22:18:10.436546284 +0100
Touching file..
SSHFS: 2017-09-19 22:18:10.000000000 +0100
Local: 2017-09-19 22:18:12.444532818 +0100
[...]
```

**Comment by ewirch** [comment]
The issue title was not accurate. We clarified already that new files are reported immediately. I updated the title accordingly. I updated your script to demonstrate the problem. It seems that the file has to exceed some size to be "cached" forever.

`issue_93d.sh`
```bash
#!/bin/sh

mkdir /tmp/issue_93
touch /tmp/issue_93/file_1
mkdir /tmp/issue_93_mnt

dd if=/dev/urandom count=1 bs=2048 |base64 > /tmp/issue_93/file_1

sshfs -f -o attr_timeout=1,entry_timeout=1,dir_cache=no \
        localhost:/tmp/issue_93/ /tmp/issue_93_mnt/ &
sleep 1
stat --format='SSHFS: %y' /tmp/issue_93_mnt/file_1
stat --format='Local: %y' /tmp/issue_93/file_1
tail -n 3 /tmp/issue_93_mnt/file_1


sleep 1
echo "Changing file.."
echo -e "\nrevision 2" >> /tmp/issue_93/file_1

stat --format='SSHFS: %y' /tmp/issue_93_mnt/file_1
stat --format='Local: %y' /tmp/issue_93/file_1

echo -e "\nSSHFS"
tail -n 3 /tmp/issue_93_mnt/file_1
echo -e "\nLocal"
tail -n 3 /tmp/issue_93/file_1

fusermount -u /tmp/issue_93_mnt/

rm -r /tmp/issue_93 /tmp/issue_93_mnt
```

Output on my system:

```
1+0 records in
1+0 records out
2048 bytes (2,0 kB, 2,0 KiB) copied, 1,9712e-05 s, 104 MB/s
ew@localhost's password: 
SSHFS: 2017-09-20 09:35:09.000000000 +0200
Local: 2017-09-20 09:35:09.030380663 +0200
XNTjL+YY08zVmkPqVe0fK3kIfSMQ7Q89RXwF18WrEAqavMwccOqq6VNDhPaQ0TX9A3qeeXPFmzhb
pcYHtEWAsxL9EnYORWIes8/90Hwo1oMiFrDxAWXpYgMTk/z6qdd67iKyA8y5b+ep46BJFCPNWddp
Z0L24C/xDp22JhEZZgTJ2zkxyVqDbrrVBIEpfRA/xxz9J8gSRmWMLd9zMDl8bJj4H18vfGw=
Changing file..
SSHFS: 2017-09-20 09:35:09.000000000 +0200
Local: 2017-09-20 09:35:11.923734627 +0200

SSHFS
XNTjL+YY08zVmkPqVe0fK3kIfSMQ7Q89RXwF18WrEAqavMwccOqq6VNDhPaQ0TX9A3qeeXPFmzhb
pcYHtEWAsxL9EnYORWIes8/90Hwo1oMiFrDxAWXpYgMTk/z6qdd67iKyA8y5b+ep46BJFCPNWddp
Z0L24C/xDp22JhEZZgTJ2zkxyVqDbrrVBIEpfRA/xxz9J8gSRmWMLd9zMDl8bJj4H18vfGw=

Local
Z0L24C/xDp22JhEZZgTJ2zkxyVqDbrrVBIEpfRA/xxz9J8gSRmWMLd9zMDl8bJj4H18vfGw=

revision 2
```

**Comment by Nikratio** [comment]
Hmm. The unchanged contents may just be a consequence of the outdated file size. If you change the `stat` calls to include the size (`%s` placeholder) you will see that when retrieving the "updated" file contents, SSHFS still reports the old (shorter) file size. The kernel probably does not attempt to read beyond that size.

If you enable debug output for sshfs (`-d`), you will see that even with the increased file size SSHFS does ask the server for updated attributes, but the server seems to return the old values. Now if only I knew why...

**Comment by Nikratio** [comment]
Alright, it turns out I was wrong. The server is reporting the correct values, and SSHFS is sending the right values to the kernel. But somehow the kernel isn't using them. With the attached patch to SSHFS, the problem is obvious:

```
$ ../issue_93.sh 
1+0 records in
1+0 records out
2048 bytes (2.0 kB, 2.0 KiB) copied, 5.8072e-05 s, 35.3 MB/s
SSHFS:  mtime 0, size 0 for /.Trash
SSHFS:  mtime 0, size 0 for /.Trash-1000
SSHFS:  mtime 1505899337, size 2768 for /file_1
SSHFS:  mtime 1505899337, size 2768 for /file_1
Kernel: mtime 1505899337, size 2768 for /tmp/issue_93_mnt/file_1
Local:  mtime 1505899337, size 2768 for /tmp/issue_93/file_1
Changing file..
SSHFS:  mtime 1505899339, size 2780 for /file_1
SSHFS:  mtime 1505899339, size 2780 for /file_1
Kernel: mtime 1505899337, size 2768 for /tmp/issue_93_mnt/file_1
Local:  mtime 1505899339, size 2780 for /tmp/issue_93/file_1
```

Unfortunately, the solution isn't as obvious as the problem. I also don't understand why getattr() seems to be called twice for each stat - might be related?

**Comment by Nikratio** [comment]
The problem actually disappears when writeback caching is disabled. Interesting.

**Comment by Nikratio** [comment]
...and apparently sometimes, the problem is also caught by the unit tests: https://travis-ci.org/libfuse/sshfs/builds/277712747
