### ISSUE TITLE
wrong man-page location

### ISSUE THREAD

**Issue by fjaell** [libfuse/sshfs#95]
sshfs 3.3.0 installs the man-page into 
    
man/1/sshfs.1 instead of 
man/man1/sshfs.1

Trivial fix:

`sed -i '/mandir/s/1/man1/' meson.build`

Please consider to ship a pre-build man-page with the sources to avoid the dependency to python-docutils.

Thanks

**Comment by Nikratio** [comment]
Thanks for the report! Would love to ship a pre-rendered manpage, but I believe that's not possible with Meson. Patches welcome!
