### ISSUE TITLE
mount.sshfs fails with error "fuse: unknown options(s):"

### ISSUE THREAD

**Issue by maxchaos** [libfuse/sshfs#96]
After a recent update of my Arch machine, I have been unable to mount remote filesystems of type "fuse.sshfs" using the mount utility, which fails with the following error message:
`fuse: unknown option(s): -o user`
This is probably caused by the option _user_ in my corresponding _/etc/fstab_ entry, which is necessary for non-root users to be able to manually mount filesystems.

I have noticed that the previous mount helper (i.e., _mount.fuse_) had a certain [set of command-line arguments which were ignored](https://github.com/libfuse/libfuse/blob/44346a9885cb4567ea29c4cb089b1f249c0e46c2/util/mount.fuse.c#L155) by default, with _user_ and __netdev_ being among them.

Shouldn't _mount.sshfs_ also ignore these arguments as well?

There is also a discussion regarding this issue on the Arch forum:
https://bbs.archlinux.org/viewtopic.php?id=230191

**Comment by Nikratio** [comment]
Right you are, thanks for the report!
